/** Generated by scripts/build-ma-public-snapshot.py. Do not edit by hand. */
export const MA_PUBLIC_SNAPSHOT = {
  "version": "senior-ma-state-intel-v1",
  "ticket": "MA-SEN-001",
  "publicationPath": "/massachusetts",
  "asOf": "2026-09-24",
  "snapshotAsOf": "2026-09-24",
  "retrievedAt": "2026-09-24T16:37:44Z",
  "generatedAt": "2026-09-24T17:00:00Z",
  "localWorkNeededNow": "NO",
  "claimEligibilityBroadened": false,
  "no_trust_score": true,
  "no_aggregate_rating": true,
  "no_rankings": true,
  "no_boston_page": true,
  "clocks": {
    "generatedAt": "2026-09-24T17:00:00Z",
    "snapshotAsOf": "2026-09-24",
    "dph_workbook_sourceAsOf": "2026-09-08",
    "dph_workbook_retrievedAt": "2026-09-24T16:37:44Z",
    "alr_list_sourceAsOf": "2026-06-25",
    "alr_list_retrievedAt": "2026-09-24T16:37:52Z",
    "alr_census_report_period": "Calendar year 2025; data as of 2025-12-31",
    "alr_census_report_retrievedAt": "2026-09-24T16:37:59Z",
    "survey_tool_processed_through": "2026-09-04",
    "survey_tool_observedAt": "2026-09-24T16:38:59Z",
    "cms_nursing_home_sourceAsOf": "2026-08-01T00:00:00+00:00",
    "cms_home_health_sourceAsOf": "2026-05-27T00:00:00+00:00",
    "cms_hospice_sourceAsOf": "2026-08-19T00:00:00+00:00",
    "license_effective_date": null,
    "license_expiration_date": null,
    "retrievedAt_is_not_sourceAsOf": true,
    "cms_date_is_not_massachusetts_license_date": true
  },
  "regulatorMap": {
    "dph": "Massachusetts Department of Public Health, Division of Health Care Facility Licensure and Certification",
    "age": "Massachusetts Executive Office of Aging & Independence (AGE)",
    "dphFacilityList": "https://www.mass.gov/info-details/find-information-about-licensed-or-certified-health-care-facilities",
    "alrProgram": "https://www.mass.gov/assisted-living-residences",
    "alrDirectory": "https://www.mass.gov/assisted-living-residences/locations",
    "alrReports": "https://www.mass.gov/lists/annual-assisted-living-residence-alr-data-reports",
    "surveyTool": "https://eohhs.ehs.state.ma.us/nursehome/Default.aspx",
    "surveyToolGuide": "https://www.mass.gov/guides/nursing-home-survey-performance-tool",
    "nursingHomeConsumerInfo": "https://www.mass.gov/nursing-home-consumer-information",
    "closures": "https://www.mass.gov/info-details/information-about-nursing-home-closures",
    "cmsCareCompare": "https://www.medicare.gov/care-compare/"
  },
  "cmsOverlay": {
    "nursingHomes": 341,
    "homeHealth": 287,
    "hospice": 77,
    "source": "senior-national-intelligence.json geography MA (CMS class directories)",
    "asOf": "2026-08-27",
    "nationalFingerprint": "215b9d6301a9759f53dd92324930803089d319f95fe5e46739cbbd5f326c3294",
    "addedToNationalTotals": false,
    "censusConfirmation": {
      "artifact": "artifacts/senior-metric-census-r2-03.json",
      "nursingHomes": 341,
      "homeHealth": 287,
      "hospice": 77
    },
    "clocks": {
      "nursingHomes": {
        "datasetKey": "nursing-home-provider-information",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/4pq5-n9py",
        "sourceModifiedAt": "2026-08-01T00:00:00+00:00",
        "retrievedAt": "2026-08-26T20:24:52.158102+00:00",
        "sourcePeriod": null
      },
      "homeHealth": {
        "datasetKey": "home-health-care-agencies",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/6jpm-sxkc",
        "sourceModifiedAt": "2026-05-27T00:00:00+00:00",
        "retrievedAt": "2026-08-26T21:08:16.274819+00:00",
        "sourcePeriod": null
      },
      "hospice": {
        "datasetKey": "hospice-general-information",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/yc9t-dgbk",
        "sourceModifiedAt": "2026-08-19T00:00:00+00:00",
        "retrievedAt": "2026-08-26T22:15:06.243039+00:00",
        "sourcePeriod": null
      },
      "inspections": {
        "datasetKey": "nursing-home-inspection-dates",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/svdt-c123",
        "sourceModifiedAt": "2026-08-01T00:00:00+00:00",
        "retrievedAt": "2026-08-26T20:18:10.260419+00:00",
        "sourcePeriod": null
      },
      "ownership": {
        "datasetKey": "skilled-nursing-facility-all-owners",
        "officialUrl": "https://data.cms.gov/provider-characteristics/hospitals-and-other-facilities/skilled-nursing-facility-all-owners",
        "sourceModifiedAt": "2026-08-17T00:00:00+00:00",
        "retrievedAt": "2026-08-26T20:25:26.251400+00:00",
        "sourcePeriod": "2026-08-01/2026-08-31"
      },
      "penalties": {
        "datasetKey": "nursing-home-penalties",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/g6vv-u9sr",
        "sourceModifiedAt": "2026-08-01T00:00:00+00:00",
        "retrievedAt": "2026-08-26T20:24:35.184131+00:00",
        "sourcePeriod": null
      }
    }
  },
  "dphWorkbook": {
    "source": "https://www.mass.gov/doc/list-of-health-care-facilities-licensed-or-certified-by-the-division/download",
    "sourceAsOf": "2026-09-08",
    "retrievedAt": "2026-09-24T16:37:44Z",
    "sha256": "163b969767c5248529df21e34c0578e9879243029620248c3f99feaafad3a4a6",
    "rowsAllTypes": 3418,
    "typesInWorkbook": 23,
    "seniorTypesTaken": [
      "Nursing Home",
      "Rest Home",
      "Certified Home Health Agency",
      "Hospice",
      "Hospice Inpatient Satellite",
      "Adult Day Health"
    ],
    "otherTypesExcluded": [
      "Acute Hospital",
      "Ambulatory Surgical Ctr.",
      "Clinic",
      "Clinic Satellite",
      "Hospital Satellite",
      "ICFIID",
      "Mob/Port Hospital Satellite",
      "Mobile/Portable Clinic",
      "Mobile/Portable Clinic Satellite",
      "Non-acute Hospital",
      "Organ Procurement",
      "Outpt. Phys. Ther/Speech Path.",
      "Renal Dialysis (ESRD)",
      "Satellite Emergency Facility",
      "Satellite Inpatient Unit",
      "Stem Cell Research",
      "Temp. Nursing Agency"
    ],
    "columns": [
      "Type of Facility",
      "DPH Facility ID Number",
      "Name of Facility",
      "Street",
      "City/Town",
      "Zip Code",
      "Telephone",
      "Bed Count (if applicable)",
      "Adult Day Health Capacity (if applicable)"
    ],
    "ccnInSource": false,
    "statusField": "NONE_IN_SOURCE"
  },
  "nursingHomes": {
    "rows": 347,
    "distinctDphFacilityIds": 347,
    "bedsSum": 39889,
    "rowsWithBeds": 347,
    "source": "DPH Licensed or Certified Health Care Facility/Agency Listing",
    "sourceAsOf": "2026-09-08",
    "retrievedAt": "2026-09-24T16:37:44Z",
    "capability": "KNOWN",
    "statusField": "NONE_IN_SOURCE",
    "ccnInSource": false,
    "distinctFromRestHome": true,
    "distinctFromCmsNursingHome": true
  },
  "restHomes": {
    "rows": 58,
    "distinctDphFacilityIds": 58,
    "bedsSum": 2002,
    "rowsWithBeds": 58,
    "source": "DPH Licensed or Certified Health Care Facility/Agency Listing",
    "sourceAsOf": "2026-09-08",
    "retrievedAt": "2026-09-24T16:37:44Z",
    "capability": "KNOWN",
    "statusField": "NONE_IN_SOURCE",
    "ccnInSource": false,
    "definition": "Supportive residential setting for people who need 24-hour supervision but not routine nursing or medical care.",
    "distinctFromNursingHome": true,
    "distinctFromAssistedLiving": true
  },
  "homeHealth": {
    "rows": 325,
    "distinctDphFacilityIds": 325,
    "bedsSum": null,
    "rowsWithBeds": 0,
    "source": "DPH Licensed or Certified Health Care Facility/Agency Listing",
    "sourceAsOf": "2026-09-08",
    "retrievedAt": "2026-09-24T16:37:44Z",
    "capability": "KNOWN",
    "statusField": "NONE_IN_SOURCE",
    "ccnInSource": false,
    "stateTypeLabel": "Certified Home Health Agency",
    "distinctFromCmsHomeHealth": true
  },
  "hospice": {
    "rows": 93,
    "distinctDphFacilityIds": 93,
    "bedsSum": null,
    "rowsWithBeds": 0,
    "source": "DPH Licensed or Certified Health Care Facility/Agency Listing",
    "sourceAsOf": "2026-09-08",
    "retrievedAt": "2026-09-24T16:37:44Z",
    "capability": "KNOWN",
    "statusField": "NONE_IN_SOURCE",
    "ccnInSource": false,
    "distinctFromCmsHospice": true
  },
  "hospiceInpatientSatellites": {
    "rows": 6,
    "distinctDphFacilityIds": 6,
    "bedsSum": 94,
    "rowsWithBeds": 6,
    "source": "DPH Licensed or Certified Health Care Facility/Agency Listing",
    "sourceAsOf": "2026-09-08",
    "retrievedAt": "2026-09-24T16:37:44Z",
    "capability": "KNOWN",
    "statusField": "NONE_IN_SOURCE",
    "ccnInSource": false,
    "subUnitOfHospiceProgram": true,
    "notAddedToHospiceRows": true
  },
  "adultDayHealth": {
    "rows": 162,
    "distinctDphFacilityIds": 162,
    "bedsSum": null,
    "rowsWithBeds": 0,
    "source": "DPH Licensed or Certified Health Care Facility/Agency Listing",
    "sourceAsOf": "2026-09-08",
    "retrievedAt": "2026-09-24T16:37:44Z",
    "capability": "KNOWN",
    "statusField": "NONE_IN_SOURCE",
    "ccnInSource": false,
    "capacitySum": 16685,
    "notResidential": true
  },
  "assistedLiving": {
    "rows": 272,
    "statusCounts": {
      "Certified": 271,
      "(date in status column: 1996-05-20)": 1
    },
    "totalUnits": 19300,
    "traditionalUnits": 13904,
    "specialCareUnits": 5396,
    "maxOccupancy": 21750,
    "residencesWithSpecialCareUnits": 204,
    "unitGrain": "units reported on the AGE list; not residents and not beds",
    "regulator": "Executive Office of Aging & Independence (AGE)",
    "credential": "ALR certification (not a DPH license, not CMS certification)",
    "source": "https://mass.gov/doc/list-of-certified-assisted-living-residences-as-of-april-2025/download",
    "sourceTitle": "Certified Assisted Living Residences (ALR) in Massachusetts as of June 25, 2026",
    "sourceAsOf": "2026-06-25",
    "retrievedAt": "2026-09-24T16:37:52Z",
    "sha256": "8138c184ee099c7b5242cbdfb355ee03bd9392526c2b0f9bfb25fe29a6d7d7e7",
    "fieldsWithheld": [
      "Executive Director",
      "ED email",
      "RCD NAME",
      "RCD Email",
      "RCD History",
      "ED Change History",
      "additional e-mails",
      "Federal ID #",
      "Staff updating"
    ],
    "liveDirectoryObservation": {
      "results": 273,
      "observedAt": "2026-09-24T16:37:52Z",
      "url": "https://www.mass.gov/assisted-living-residences/locations",
      "rowsAcquired": null,
      "note": "The live Mass.gov location listing showed 273 results; the downloadable list (as of the date above) has the rows used here."
    },
    "capability": "KNOWN",
    "distinctFromRestHome": true,
    "distinctFromNursingHome": true
  },
  "alrCensus2026": {
    "source": "https://www.mass.gov/doc/assisted-living-residences-census-report-2026/download",
    "retrievedAt": "2026-09-24T16:37:59Z",
    "reportPeriod": "Calendar year 2025 (data as of 2025-12-31)",
    "statedCertifiedAlrsJanuary2026": 272,
    "respondingAlrs": 268,
    "usedAsIdentitySource": false,
    "capability": "KNOWN"
  },
  "surveyTool": {
    "name": "DPH Nursing Home Survey Performance Tool",
    "url": "https://eohhs.ehs.state.ma.us/nursehome/Default.aspx",
    "processedThrough": "2026-09-04",
    "listedFacilities": 343,
    "observedAt": "2026-09-24T16:38:59Z",
    "method": "Tool's own methodology: 132 items reviewed across the last 3 standard surveys (44 per survey). Not a TrustHub score.",
    "facilityIdentifiersInListing": false,
    "indexedFacilityResults": null,
    "capability": "KNOWN",
    "bulkCapability": "NOT_ACQUIRED",
    "reason": "Results are reached through paged ASP.NET postbacks and per-facility pages with truncated names and no IDs. Not backfilled.",
    "notTrustHubScore": true
  },
  "complaints": {
    "intake": "KNOWN",
    "providerLevelRows": null,
    "capability": "REQUEST_ONLY",
    "complaintIsNotDeficiency": true
  },
  "closures": {
    "page": "https://www.mass.gov/info-details/information-about-nursing-home-closures",
    "rows": null,
    "capability": "NOT_ACQUIRED",
    "reason": "Closure notices are individual PDF/Word filings; not parsed."
  },
  "massgis": {
    "capability": "UNSUPPORTED",
    "reason": "MassGIS Long-Term Care Residences (March 2024 release, sources from late 2023) is not a current roster."
  },
  "crosswalk": {
    "exactStateToCmsBridges": 0,
    "attempted": true,
    "method": "exact CCN in state source",
    "ccnInDphWorkbook": false,
    "nameOnly": "UNSAFE",
    "addressResolver": "NOT_USED (no accepted address resolver contract for state-to-CMS joins)",
    "dphNursingHomeRowsUnresolved": 347,
    "cmsNursingHomeRowsUnresolved": 341,
    "capability": "UNKNOWN",
    "reason": "The DPH workbook has no CCN, so no exact bridge exists. Zero bridges is not zero overlap: most DPH nursing homes are likely CMS-certified, but that is not established here."
  },
  "cityContext": {
    "grain": "facility rows with that city in the source address; not a local page",
    "cities": {
      "Boston": {
        "nursingHomes": 17,
        "restHomes": 7,
        "assistedLivingResidences": 9,
        "homeHealth": 19,
        "hospice": 1
      },
      "Worcester": {
        "nursingHomes": 16,
        "restHomes": 8,
        "assistedLivingResidences": 6,
        "homeHealth": 28,
        "hospice": 4
      },
      "Springfield": {
        "nursingHomes": 2,
        "restHomes": 2,
        "assistedLivingResidences": 3,
        "homeHealth": 18,
        "hospice": 1
      }
    }
  },
  "expansionLedger": {
    "NET_NEW_STATE_RESEARCH_IDENTITIES": 1263,
    "NET_NEW_CANONICAL_FACILITIES": 0,
    "NET_NEW_PUBLIC_PROFILES": 0,
    "EXISTING_FACILITIES_ENRICHED": 0,
    "GRAPH_WRITES": 0,
    "CLAIM_ELIGIBILITY_BROADENED": false
  },
  "capabilities": [
    {
      "id": "cms-nursing-home-ma",
      "state": "KNOWN"
    },
    {
      "id": "cms-home-health-ma",
      "state": "KNOWN"
    },
    {
      "id": "cms-hospice-ma",
      "state": "KNOWN"
    },
    {
      "id": "dph-facility-workbook",
      "state": "KNOWN"
    },
    {
      "id": "dph-nursing-home-rows",
      "state": "KNOWN"
    },
    {
      "id": "dph-rest-home-rows",
      "state": "KNOWN"
    },
    {
      "id": "dph-home-health-rows",
      "state": "KNOWN"
    },
    {
      "id": "dph-hospice-rows",
      "state": "KNOWN"
    },
    {
      "id": "dph-adult-day-health-rows",
      "state": "KNOWN"
    },
    {
      "id": "age-alr-list",
      "state": "KNOWN"
    },
    {
      "id": "age-alr-census-2026-context",
      "state": "KNOWN"
    },
    {
      "id": "dph-survey-performance-tool",
      "state": "KNOWN"
    },
    {
      "id": "dph-survey-results-bulk",
      "state": "NOT_ACQUIRED"
    },
    {
      "id": "dph-license-status-or-expiration",
      "state": "UNKNOWN"
    },
    {
      "id": "dph-provider-complaints",
      "state": "REQUEST_ONLY"
    },
    {
      "id": "nursing-home-closure-list",
      "state": "NOT_ACQUIRED"
    },
    {
      "id": "exact-state-to-cms-join",
      "state": "UNKNOWN"
    },
    {
      "id": "name-only-state-to-cms-join",
      "state": "UNSUPPORTED"
    },
    {
      "id": "massgis-as-current-roster",
      "state": "UNSUPPORTED"
    },
    {
      "id": "combined-massachusetts-senior-facilities",
      "state": "UNSUPPORTED"
    }
  ],
  "fingerprint": "b8cb397f6bb0ecdb9f58a09ff7e6a7ce720d7a37c1906cf16e68deac39586ccf"
} as const;
export type MaPublicSnapshot = typeof MA_PUBLIC_SNAPSHOT;
