/** Generated by scripts/build-nj-public-snapshot.py. Do not edit by hand. */
export const NJ_PUBLIC_SNAPSHOT = {
  "version": "nj-sen-005-public-v1",
  "asOf": "2026-09-02",
  "ltcAsOf": "2026-08-31",
  "acuteAsOf": "2026-08-31",
  "ltc": {
    "rows": 893,
    "uniqueFacIds": 893,
    "uniqueLicenses": 893,
    "types": 19,
    "counties": 21,
    "quarantined": 0,
    "byType": [
      {
        "label": "LONG TERM CARE FACILITY SNF/NF",
        "count": 303
      },
      {
        "label": "ASSISTED LIVING RESIDENCE",
        "count": 256
      },
      {
        "label": "ADULT DAY HEALTH SERVICES FACILITY",
        "count": 159
      },
      {
        "label": "COMPREHENSIVE PERSONAL CARE HOME",
        "count": 32
      },
      {
        "label": "RESIDENTIAL DEMENTIA CARE HOME",
        "count": 31
      },
      {
        "label": "LONG TERM CARE FACILITY - HOME FOR THE AGED SNF/NF",
        "count": 23
      },
      {
        "label": "ASSISTED LIVING PROGRAM",
        "count": 17
      },
      {
        "label": "LONG TERM CARE FACILITY",
        "count": 15
      },
      {
        "label": "PEDIATRIC DAY HEALTH SERVICES FACILITY",
        "count": 13
      },
      {
        "label": "RESIDENTIAL HEALTH CARE in a LONG-TERM CARE FACILITY",
        "count": 10
      },
      {
        "label": "LONG TERM CARE FACILITY S/NF DP",
        "count": 7
      },
      {
        "label": "ADULT DAY HEALTH SERVICES in a LONG-TERM CARE FACILITY",
        "count": 6
      },
      {
        "label": "HOSPITAL BASED - LONG TERM CARE FACILITY SNF/NF",
        "count": 6
      },
      {
        "label": "LONG TERM CARE FACILITY LTC-PRIV",
        "count": 5
      },
      {
        "label": "HOSPITAL BASED - LONG TERM CARE SUB ACUTE FACILITY SNF",
        "count": 4
      },
      {
        "label": "ALTERNATE FAMILY CARE",
        "count": 3
      },
      {
        "label": "ADULT DAY HEALTH SERVICES in an ASSISTED LIVING RESIDENCE",
        "count": 1
      },
      {
        "label": "HOSPITAL BASED - ADULT DAY HEALTH SERVICES",
        "count": 1
      },
      {
        "label": "LONG TERM CARE FACILITY - HOME FOR THE AGED LTC-PRIV",
        "count": 1
      }
    ],
    "source": "https://healthapps.nj.gov/facilities/documents2/All_LTC.xlsx",
    "sha256": "d77ed7c9536a9c1d3c4a84286f49dad05ae9b4207f01b8aa10a9a31c6e4def1e"
  },
  "acute": {
    "rows": 1430,
    "types": 26,
    "counties": 21,
    "hha": 39,
    "hospiceProgram": 68,
    "hospiceBranch": 27,
    "hospiceInpatient": 9,
    "other": 1287,
    "quarantined": 0,
    "invalidCountyRows": 18,
    "byType": [
      {
        "label": "AMBULATORY CARE FACILITY",
        "count": 372
      },
      {
        "label": "AMBULATORY SURGICAL CENTER",
        "count": 248
      },
      {
        "label": "HOSPITAL-BASED, OFF-SITE AMBULATORY CARE FACILITY STHSPOFF",
        "count": 220
      },
      {
        "label": "END STAGE RENAL DIALYSIS",
        "count": 185
      },
      {
        "label": "GENERAL ACUTE CARE HOSPITAL",
        "count": 69
      },
      {
        "label": "HOSPICE CARE PROGRAM",
        "count": 68
      },
      {
        "label": "FEDERALLY QUALIFIED HEALTH CENTERS",
        "count": 48
      },
      {
        "label": "HOME HEALTH AGENCY",
        "count": 39
      },
      {
        "label": "AMBULATORY SURGICAL CENTER ASC-ST",
        "count": 30
      },
      {
        "label": "AMBULATORY CARE FACILITY - SATELLITE",
        "count": 29
      },
      {
        "label": "HOSPICE CARE BRANCH",
        "count": 27
      },
      {
        "label": "SURGICAL PRACTICE",
        "count": 15
      },
      {
        "label": "COMPREHENSIVE REHABILITATION HOSPITAL",
        "count": 12
      },
      {
        "label": "SPECIAL HOSPITAL HOSP-LT",
        "count": 12
      },
      {
        "label": "HOSPITAL-BASED, OFF-SITE AMBULATORY CARE FACILITY CTR ST",
        "count": 10
      },
      {
        "label": "PSYCHIATRIC HOSPITAL",
        "count": 10
      },
      {
        "label": "HOSPICE CARE - INPATIENT",
        "count": 9
      },
      {
        "label": "COMPREHENSIVE OUTPATIENT REHAB",
        "count": 8
      },
      {
        "label": "SURGICAL PRACTICE ASC-P-C",
        "count": 6
      },
      {
        "label": "HOSPITAL-BASED, OFF-SITE AMBULATORY CARE FACILITY",
        "count": 3
      },
      {
        "label": "MATERNAL AND CHILD HEALTH CONSORTIUM",
        "count": 3
      },
      {
        "label": "CHILDREN REHABILITATION HOSPITAL",
        "count": 2
      },
      {
        "label": "SPECIAL HOSPITAL HOSP-ACU",
        "count": 2
      },
      {
        "label": "HOSPITAL-BASED, OFF-SITE AMBULATORY CARE FACILITY CORF",
        "count": 1
      },
      {
        "label": "SPECIAL HOSPITAL",
        "count": 1
      },
      {
        "label": "SPECIAL HOSPITAL - PSYCHIATRIC",
        "count": 1
      }
    ],
    "source": "https://healthapps.nj.gov/facilities/documents2/All_Acute.xlsx",
    "sha256": "271569d4b4113747e161df8911ccd9dc93bc2057c27e2b9c9a6eb5f879ed6e12"
  },
  "counties": [
    {
      "county": "Atlantic",
      "ltc": 28,
      "acute": 64,
      "nfSnf": 10,
      "alr": 11,
      "cpch": 0,
      "alp": 1,
      "hha": 2,
      "hospiceProgram": 3,
      "hospiceBranch": 4,
      "hospiceInpatient": 0
    },
    {
      "county": "Bergen",
      "ltc": 91,
      "acute": 167,
      "nfSnf": 24,
      "alr": 28,
      "cpch": 3,
      "alp": 1,
      "hha": 5,
      "hospiceProgram": 7,
      "hospiceBranch": 0,
      "hospiceInpatient": 1
    },
    {
      "county": "Burlington",
      "ltc": 43,
      "acute": 77,
      "nfSnf": 11,
      "alr": 15,
      "cpch": 3,
      "alp": 3,
      "hha": 3,
      "hospiceProgram": 6,
      "hospiceBranch": 2,
      "hospiceInpatient": 1
    },
    {
      "county": "Camden",
      "ltc": 52,
      "acute": 88,
      "nfSnf": 19,
      "alr": 13,
      "cpch": 3,
      "alp": 3,
      "hha": 3,
      "hospiceProgram": 6,
      "hospiceBranch": 2,
      "hospiceInpatient": 1
    },
    {
      "county": "Cape May",
      "ltc": 12,
      "acute": 16,
      "nfSnf": 6,
      "alr": 2,
      "cpch": 2,
      "alp": 0,
      "hha": 1,
      "hospiceProgram": 0,
      "hospiceBranch": 1,
      "hospiceInpatient": 0
    },
    {
      "county": "Cumberland",
      "ltc": 16,
      "acute": 32,
      "nfSnf": 5,
      "alr": 4,
      "cpch": 1,
      "alp": 0,
      "hha": 1,
      "hospiceProgram": 2,
      "hospiceBranch": 0,
      "hospiceInpatient": 0
    },
    {
      "county": "Essex",
      "ltc": 76,
      "acute": 125,
      "nfSnf": 29,
      "alr": 15,
      "cpch": 4,
      "alp": 1,
      "hha": 4,
      "hospiceProgram": 5,
      "hospiceBranch": 2,
      "hospiceInpatient": 0
    },
    {
      "county": "Gloucester",
      "ltc": 33,
      "acute": 49,
      "nfSnf": 7,
      "alr": 14,
      "cpch": 3,
      "alp": 2,
      "hha": 0,
      "hospiceProgram": 0,
      "hospiceBranch": 0,
      "hospiceInpatient": 0
    },
    {
      "county": "Hudson",
      "ltc": 30,
      "acute": 88,
      "nfSnf": 11,
      "alr": 1,
      "cpch": 1,
      "alp": 0,
      "hha": 3,
      "hospiceProgram": 1,
      "hospiceBranch": 0,
      "hospiceInpatient": 0
    },
    {
      "county": "Hunterdon",
      "ltc": 8,
      "acute": 14,
      "nfSnf": 4,
      "alr": 2,
      "cpch": 0,
      "alp": 0,
      "hha": 1,
      "hospiceProgram": 1,
      "hospiceBranch": 0,
      "hospiceInpatient": 0
    },
    {
      "county": "Mercer",
      "ltc": 42,
      "acute": 59,
      "nfSnf": 13,
      "alr": 12,
      "cpch": 1,
      "alp": 3,
      "hha": 1,
      "hospiceProgram": 2,
      "hospiceBranch": 1,
      "hospiceInpatient": 1
    },
    {
      "county": "Middlesex",
      "ltc": 81,
      "acute": 109,
      "nfSnf": 23,
      "alr": 16,
      "cpch": 1,
      "alp": 1,
      "hha": 2,
      "hospiceProgram": 6,
      "hospiceBranch": 0,
      "hospiceInpatient": 0
    },
    {
      "county": "Monmouth",
      "ltc": 86,
      "acute": 99,
      "nfSnf": 32,
      "alr": 33,
      "cpch": 1,
      "alp": 0,
      "hha": 2,
      "hospiceProgram": 5,
      "hospiceBranch": 3,
      "hospiceInpatient": 0
    },
    {
      "county": "Morris",
      "ltc": 64,
      "acute": 86,
      "nfSnf": 21,
      "alr": 23,
      "cpch": 2,
      "alp": 0,
      "hha": 3,
      "hospiceProgram": 4,
      "hospiceBranch": 2,
      "hospiceInpatient": 1
    },
    {
      "county": "Ocean",
      "ltc": 63,
      "acute": 95,
      "nfSnf": 29,
      "alr": 19,
      "cpch": 2,
      "alp": 1,
      "hha": 3,
      "hospiceProgram": 5,
      "hospiceBranch": 7,
      "hospiceInpatient": 0
    },
    {
      "county": "Passaic",
      "ltc": 47,
      "acute": 84,
      "nfSnf": 13,
      "alr": 10,
      "cpch": 0,
      "alp": 0,
      "hha": 2,
      "hospiceProgram": 2,
      "hospiceBranch": 0,
      "hospiceInpatient": 1
    },
    {
      "county": "Salem",
      "ltc": 10,
      "acute": 10,
      "nfSnf": 4,
      "alr": 3,
      "cpch": 1,
      "alp": 0,
      "hha": 0,
      "hospiceProgram": 0,
      "hospiceBranch": 1,
      "hospiceInpatient": 0
    },
    {
      "county": "Somerset",
      "ltc": 45,
      "acute": 51,
      "nfSnf": 12,
      "alr": 21,
      "cpch": 0,
      "alp": 0,
      "hha": 1,
      "hospiceProgram": 4,
      "hospiceBranch": 1,
      "hospiceInpatient": 0
    },
    {
      "county": "Sussex",
      "ltc": 10,
      "acute": 15,
      "nfSnf": 4,
      "alr": 4,
      "cpch": 1,
      "alp": 0,
      "hha": 0,
      "hospiceProgram": 1,
      "hospiceBranch": 1,
      "hospiceInpatient": 1
    },
    {
      "county": "Union",
      "ltc": 46,
      "acute": 74,
      "nfSnf": 19,
      "alr": 8,
      "cpch": 3,
      "alp": 1,
      "hha": 1,
      "hospiceProgram": 4,
      "hospiceBranch": 0,
      "hospiceInpatient": 2
    },
    {
      "county": "Warren",
      "ltc": 10,
      "acute": 10,
      "nfSnf": 7,
      "alr": 2,
      "cpch": 0,
      "alp": 0,
      "hha": 0,
      "hospiceProgram": 0,
      "hospiceBranch": 0,
      "hospiceInpatient": 0
    }
  ],
  "staffing": {
    "populatedQuarters": 30,
    "first": "2019 Q1",
    "latest": "2026 Q2",
    "trend": [
      {
        "year": 2019,
        "quarter": "Q1",
        "label": "2019 Q1",
        "dayRn": 29.4,
        "dayLpn": 22.6,
        "dayCna": 8.8,
        "facilities": 371
      },
      {
        "year": 2019,
        "quarter": "Q2",
        "label": "2019 Q2",
        "dayRn": 29.7,
        "dayLpn": 22.4,
        "dayCna": 8.8,
        "facilities": 370
      },
      {
        "year": 2019,
        "quarter": "Q3",
        "label": "2019 Q3",
        "dayRn": 29.8,
        "dayLpn": 22.4,
        "dayCna": 8.9,
        "facilities": 370
      },
      {
        "year": 2019,
        "quarter": "Q4",
        "label": "2019 Q4",
        "dayRn": 29.7,
        "dayLpn": 22.2,
        "dayCna": 8.9,
        "facilities": 370
      },
      {
        "year": 2020,
        "quarter": "Q1",
        "label": "2020 Q1",
        "dayRn": 30.0,
        "dayLpn": 22.1,
        "dayCna": 9.1,
        "facilities": 371
      },
      {
        "year": 2020,
        "quarter": "Q2",
        "label": "2020 Q2",
        "dayRn": 26.6,
        "dayLpn": 19.5,
        "dayCna": 8.7,
        "facilities": 370
      },
      {
        "year": 2020,
        "quarter": "Q3",
        "label": "2020 Q3",
        "dayRn": 27.0,
        "dayLpn": 19.9,
        "dayCna": 8.7,
        "facilities": 370
      },
      {
        "year": 2020,
        "quarter": "Q4",
        "label": "2020 Q4",
        "dayRn": 27.4,
        "dayLpn": 20.1,
        "dayCna": 8.9,
        "facilities": 370
      },
      {
        "year": 2021,
        "quarter": "Q1",
        "label": "2021 Q1",
        "dayRn": 27.9,
        "dayLpn": 20.1,
        "dayCna": 8.8,
        "facilities": 368
      },
      {
        "year": 2021,
        "quarter": "Q2",
        "label": "2021 Q2",
        "dayRn": 29.3,
        "dayLpn": 20.6,
        "dayCna": 8.8,
        "facilities": 364
      },
      {
        "year": 2021,
        "quarter": "Q3",
        "label": "2021 Q3",
        "dayRn": 31.0,
        "dayLpn": 21.1,
        "dayCna": 9.0,
        "facilities": 364
      },
      {
        "year": 2021,
        "quarter": "Q4",
        "label": "2021 Q4",
        "dayRn": 31.6,
        "dayLpn": 21.2,
        "dayCna": 8.9,
        "facilities": 363
      },
      {
        "year": 2022,
        "quarter": "Q1",
        "label": "2022 Q1",
        "dayRn": 32.4,
        "dayLpn": 21.0,
        "dayCna": 8.8,
        "facilities": 361
      },
      {
        "year": 2022,
        "quarter": "Q2",
        "label": "2022 Q2",
        "dayRn": 32.7,
        "dayLpn": 20.8,
        "dayCna": 8.7,
        "facilities": 361
      },
      {
        "year": 2022,
        "quarter": "Q3",
        "label": "2022 Q3",
        "dayRn": 34.4,
        "dayLpn": 21.1,
        "dayCna": 9.1,
        "facilities": 360
      },
      {
        "year": 2022,
        "quarter": "Q4",
        "label": "2022 Q4",
        "dayRn": 35.0,
        "dayLpn": 20.8,
        "dayCna": 8.9,
        "facilities": 362
      },
      {
        "year": 2023,
        "quarter": "Q1",
        "label": "2023 Q1",
        "dayRn": 34.5,
        "dayLpn": 20.6,
        "dayCna": 9.0,
        "facilities": 362
      },
      {
        "year": 2023,
        "quarter": "Q2",
        "label": "2023 Q2",
        "dayRn": 35.3,
        "dayLpn": 20.6,
        "dayCna": 8.9,
        "facilities": 358
      },
      {
        "year": 2023,
        "quarter": "Q3",
        "label": "2023 Q3",
        "dayRn": 37.0,
        "dayLpn": 20.7,
        "dayCna": 9.0,
        "facilities": 359
      },
      {
        "year": 2023,
        "quarter": "Q4",
        "label": "2023 Q4",
        "dayRn": 37.2,
        "dayLpn": 20.8,
        "dayCna": 8.9,
        "facilities": 361
      },
      {
        "year": 2024,
        "quarter": "Q1",
        "label": "2024 Q1",
        "dayRn": 37.8,
        "dayLpn": 21.0,
        "dayCna": 9.1,
        "facilities": 360
      },
      {
        "year": 2024,
        "quarter": "Q2",
        "label": "2024 Q2",
        "dayRn": 38.0,
        "dayLpn": 21.0,
        "dayCna": 8.8,
        "facilities": 361
      },
      {
        "year": 2024,
        "quarter": "Q3",
        "label": "2024 Q3",
        "dayRn": 38.3,
        "dayLpn": 21.1,
        "dayCna": 8.7,
        "facilities": 362
      },
      {
        "year": 2024,
        "quarter": "Q4",
        "label": "2024 Q4",
        "dayRn": 39.7,
        "dayLpn": 20.9,
        "dayCna": 8.6,
        "facilities": 361
      },
      {
        "year": 2025,
        "quarter": "Q1",
        "label": "2025 Q1",
        "dayRn": 39.8,
        "dayLpn": 21.1,
        "dayCna": 8.6,
        "facilities": 361
      },
      {
        "year": 2025,
        "quarter": "Q2",
        "label": "2025 Q2",
        "dayRn": 39.6,
        "dayLpn": 20.9,
        "dayCna": 8.4,
        "facilities": 361
      },
      {
        "year": 2025,
        "quarter": "Q3",
        "label": "2025 Q3",
        "dayRn": 40.3,
        "dayLpn": 21.0,
        "dayCna": 8.3,
        "facilities": 361
      },
      {
        "year": 2025,
        "quarter": "Q4",
        "label": "2025 Q4",
        "dayRn": 40.5,
        "dayLpn": 20.9,
        "dayCna": 8.3,
        "facilities": 361
      },
      {
        "year": 2026,
        "quarter": "Q1",
        "label": "2026 Q1",
        "dayRn": 40.8,
        "dayLpn": 21.4,
        "dayCna": 8.5,
        "facilities": 361
      },
      {
        "year": 2026,
        "quarter": "Q2",
        "label": "2026 Q2",
        "dayRn": 40.5,
        "dayLpn": 21.0,
        "dayCna": 8.3,
        "facilities": 361
      }
    ],
    "semantics": "Official values are residents per one staff member (1RN:#Res). Missing codes are not zero.",
    "notAttachedTo": [
      "ALR",
      "CPCH",
      "ALP",
      "Home Health",
      "Hospice",
      "PACE",
      "CCRC"
    ]
  },
  "enforcement": {
    "indexed": 1146,
    "downloaded": 1144,
    "uniqueHashes": 1131,
    "unavailable": 2,
    "byClass": {
      "penalty_letter": 660,
      "directed_plan_of_correction": 100,
      "admission_curtailment": 221,
      "license_revocation": 4,
      "other_expressly_identified_njdoh_action": 113,
      "unclassified_regulatory_document": 30,
      "license_suspension": 12,
      "civil_monetary_penalty": 5,
      "corrective_action": 1
    },
    "byYear": {
      "2016": 1,
      "2017": 22,
      "2018": 35,
      "2019": 21,
      "2020": 64,
      "2021": 39,
      "2022": 60,
      "2023": 110,
      "2024": 241,
      "2025": 306,
      "2026": 247
    },
    "matchBuckets": {
      "EXACT": 300,
      "UNSAFE_REJECTED": 291,
      "UNRESOLVED": 476,
      "REVIEW_REQUIRED": 3,
      "HIGH_CONFIDENCE": 76
    },
    "exactFacilities": 224,
    "coverage": "ACQUIRED_PARTIAL_HISTORY"
  },
  "pace": {
    "organizations": 8,
    "operatingOrganizations": 6,
    "awardedOrganizations": 2,
    "operatingCenters": 10,
    "operatingCounties": 13,
    "partialCounties": 3,
    "zipRecords": 38,
    "awardedFutureCounties": 8,
    "organizationsList": [
      {
        "name": "Capital Health LIFE",
        "status": "OPERATING"
      },
      {
        "name": "Trinity Health LIFE New Jersey",
        "status": "OPERATING"
      },
      {
        "name": "Lutheran Senior LIFE",
        "status": "OPERATING"
      },
      {
        "name": "Inspira LIFE",
        "status": "OPERATING"
      },
      {
        "name": "BoldAge PACE",
        "status": "OPERATING"
      },
      {
        "name": "AtlantiCare LIFE Connection",
        "status": "OPERATING"
      },
      {
        "name": "WelbeHealth",
        "status": "AWARDED"
      },
      {
        "name": "Senior LIFE",
        "status": "AWARDED"
      }
    ],
    "centers": [
      {
        "org": "Capital Health LIFE",
        "name": "Capital Health LIFE Bordentown",
        "city": "Bordentown",
        "county": "Burlington",
        "status": "OPERATING"
      },
      {
        "org": "Trinity Health LIFE New Jersey",
        "name": "Trinity Health LIFE Pennsauken",
        "city": "Pennsauken",
        "county": "Camden",
        "status": "OPERATING"
      },
      {
        "org": "Lutheran Senior LIFE",
        "name": "Lutheran Senior LIFE at Jersey City",
        "city": "Jersey City",
        "county": "Hudson",
        "status": "OPERATING"
      },
      {
        "org": "Lutheran Senior LIFE",
        "name": "Lutheran Senior LIFE at Union",
        "city": "Plainfield",
        "county": "Union",
        "status": "OPERATING"
      },
      {
        "org": "Inspira LIFE",
        "name": "Inspira LIFE Vineland",
        "city": "Vineland",
        "county": "Cumberland",
        "status": "OPERATING"
      },
      {
        "org": "Inspira LIFE",
        "name": "Inspira LIFE Williamstown",
        "city": "Williamstown",
        "county": "Gloucester",
        "status": "OPERATING"
      },
      {
        "org": "BoldAge PACE",
        "name": "BoldAge PACE Lakehurst",
        "city": "Lakehurst",
        "county": "Ocean",
        "status": "OPERATING"
      },
      {
        "org": "BoldAge PACE",
        "name": "BoldAge PACE Oceanport",
        "city": "Oceanport",
        "county": "Monmouth",
        "status": "OPERATING"
      },
      {
        "org": "BoldAge PACE",
        "name": "BoldAge PACE East Brunswick",
        "city": "East Brunswick",
        "county": "Middlesex",
        "status": "OPERATING"
      },
      {
        "org": "AtlantiCare LIFE Connection",
        "name": "AtlantiCare LIFE Connection Atlantic City",
        "city": "Atlantic City",
        "county": "Atlantic",
        "status": "OPERATING"
      },
      {
        "org": "WelbeHealth",
        "name": "WelbeHealth Newark (awarded)",
        "city": "Newark",
        "county": "Essex",
        "status": "IN_DEVELOPMENT"
      },
      {
        "org": "WelbeHealth",
        "name": "WelbeHealth Paramus (awarded)",
        "city": "Paramus",
        "county": "Bergen",
        "status": "IN_DEVELOPMENT"
      },
      {
        "org": "Senior LIFE",
        "name": "Senior LIFE Bridgewater (awarded)",
        "city": "Bridgewater",
        "county": "Somerset",
        "status": "IN_DEVELOPMENT"
      },
      {
        "org": "Senior LIFE",
        "name": "Senior LIFE Wayne (awarded)",
        "city": "Wayne",
        "county": "Passaic",
        "status": "IN_DEVELOPMENT"
      }
    ],
    "notes": [
      "Current DoAS listing is the operating source. January 8, 2026 announcement is historical/awarded evidence.",
      "East Brunswick/Middlesex and Plainfield/Union moved from in-development (2026-01-08) to operating on the current DoAS page. Open date remains unknown.",
      "Camden is 'most communities' plus listed Burlington ZIPs \u2014 not full-county.",
      "Hudson and Burlington remain ZIP-listed partial counties.",
      "Eight agencies on the DoAS page is a source phrase; organizations and centers are counted separately.",
      "PACE eligibility is program metadata, not person records.",
      "First snapshot is baseline-only."
    ]
  },
  "cmsOverlay": {
    "nursingHomes": 348,
    "homeHealth": 38,
    "hospice": 61,
    "source": "senior-national-intelligence.json geography NJ",
    "asOf": "2026-08-27"
  },
  "ccrc": {
    "coverage": "SOURCE_AVAILABLE_BY_REQUEST",
    "countPublished": null
  },
  "profileAttachments": [],
  "gaps": [
    "A complete CCRC Certificate of Authority roster was not acquired from public files.",
    "The Medicaid assisted-living schedule lacks stable identifiers for many listed rows; name-only matching is withheld from profiles.",
    "NJDOH Home Health and Hospice physical office counties are not service areas.",
    "CMS Home Health/Hospice crosswalks for NJDOH rows remain incomplete without production CMS joins.",
    "Some NJDOH enforcement documents remain unresolved to a specific facility.",
    "Home Health/Hospice counties-served listings are behind an ASP.NET search POST (SOURCE_ACCESS_BLOCKED)."
  ],
  "fingerprint": "92e0742f77f2f55a5ccd6217c5caa779f3281fd26b1d91c14e2df11ae144011a",
  "medicaid": {
    "listedRows": 236,
    "minRate": 81.1,
    "maxRate": 126.1,
    "bySubtype": [
      {
        "label": "UNKNOWN_NOT_PRINTED",
        "count": 221
      },
      {
        "label": "ALR",
        "count": 7
      },
      {
        "label": "ALP",
        "count": 6
      },
      {
        "label": "CPCH",
        "count": 2
      }
    ],
    "defaults": {
      "ALP": 99.1,
      "ALR": 91.1,
      "CPCH": 81.1
    },
    "effectiveOn": "2025-07-01",
    "fiscalYear": "SFY_2026",
    "source": "https://www.njmmis.com/downloadDocuments/SFY_2026_Assisted_Living_Rates.pdf",
    "rowCount": 236
  }
} as const;
