/** Generated from artifacts/ny-sen-001-public-snapshot.json. Do not edit by hand. */
export const NY_PUBLIC_SNAPSHOT = {
  version: "senior-ny-state-intel-v1",
  ticket: "NY-SEN-001",
  asOf: null,
  retrievedAt: "2026-09-11T16:00:00Z",
  snapshotAsOf: "2026-09-11",
  generatedAt: "2026-09-11T16:00:00Z",
  regulatorMap: {
    agency: "New York State Department of Health",
    nursingHomeProfile: "https://health.data.ny.gov/Health/Nursing-Home-Profile/dypu-nabu",
    nursingHomeProfilesSite: "https://profiles.health.ny.gov/nursing_home/",
    certification:
      "https://health.data.ny.gov/Health/Health-Facility-Certification-Information/2g9y-7kqm",
    generalInformation:
      "https://health.data.ny.gov/Health/Health-Facility-General-Information/vn5v-hh5r",
    doNotRefer: "https://www.health.ny.gov/facilities/adult_care/docs/acf_do_not_refer_list.pdf",
    acfHome: "https://www.health.ny.gov/facilities/adult_care/",
    healthProfilesAcf: "https://profiles.health.ny.gov/acf/",
    cmsCareCompare: "https://www.medicare.gov/care-compare/",
  },
  uiGrains: {
    acfFacilities: "VISIBLE_PUBLIC_METRIC",
    nursingHomeFacilities: "VISIBLE_PUBLIC_METRIC",
    nursingHomeSurveys: "VISIBLE_PUBLIC_METRIC",
    doNotReferObservations: "VISIBLE_PUBLIC_METRIC",
    cmsHomeHealth: "VISIBLE_PUBLIC_METRIC",
    cmsHospice: "VISIBLE_PUBLIC_METRIC",
    nursingHomeCitations: "VISIBLE_SUPPORTING_CONTEXT",
    nursingHomeEnforcement: "VISIBLE_SUPPORTING_CONTEXT",
    nursingHomeComplaintSummary: "VISIBLE_SUPPORTING_CONTEXT",
    assistedLivingDesignations: "VISIBLE_SUPPORTING_CONTEXT",
    lhcsa: "VISIBLE_SUPPORTING_CONTEXT",
    chhaState: "VISIBLE_SUPPORTING_CONTEXT",
    adultDay: "VISIBLE_SUPPORTING_CONTEXT",
    exactCcnBridge: "VISIBLE_SUPPORTING_CONTEXT",
    operatorMembers: "INTERNAL_DIAGNOSTIC_ONLY",
  },
  nursingHomeProfile: {
    coverage: "ACQUIRED_CURRENT_SNAPSHOT",
    source: "NYSDOH Nursing Home Profile zip (Health Data NY dypu-nabu)",
    officialUrl: "https://health.data.ny.gov/Health/Nursing-Home-Profile/dypu-nabu",
    sourceAsOf: "2026-08-19",
    retrievedAt: "2026-09-11T16:00:00Z",
    grain:
      "Facility_Info.csv row = one NYSDOH nursing-home facility (FACILITY_ID unique in this extract).",
    sourceRows: 597,
    distinctFacilityIds: 597,
    duplicateFacilityIds: 0,
    rowsWithCcn: 595,
    rowsWithoutCcn: 2,
    distinctCcn: 594,
    duplicateCcnValues: 1,
    surveyRows: 6036,
    surveyFacilityCoverage: 597,
    surveyDateMin: "2024-01-02",
    surveyDateMax: "2025-12-31",
    surveyTypes: {
      COMPLAINT: 3802,
      "CERTIFICATION/COMPLAINT": 1109,
      COVID19: 1024,
      CERTIFICATION: 101,
    },
    citationRows: 19032,
    citationRowsIsComplaint1: 4244,
    enforcementRows: 2036,
    enforcementFacilityCoverage: 583,
    inspectionIsNotDeficiencyCount: true,
    complaintSurveyIsNotSubstantiatedComplaint: true,
    isComplaintFlagIsNotComplaintCount: true,
    fineIsNotCriminalConviction: true,
    enforcementRowIsNotUniqueFacility: true,
    occupancyIsNotCapacityHeadline: true,
    notCombinedWithAcf: true,
  },
  acf: {
    coverage: "PARTIAL_SOURCE_COVERAGE",
    source:
      "Health Facility General Information joined conceptually with Certification Information on Facility ID",
    sourceAsOf: "2026-09-01",
    retrievedAt: "2026-09-11T16:00:00Z",
    adultHomeFacilities: 381,
    enrichedHousingFacilities: 146,
    acfFacilities: 527,
    distinctOperatingCertificates: 527,
    ahBedCertificationRows: 1146,
    ehpBedCertificationRows: 466,
    ahEhpOverlapFacilityIds: 0,
    currentness:
      "PARTIAL \u2014 GI prints opening date and operating certificate; source does not print ACTIVE/EXPIRED. Not guessed as ACTIVE.",
    capacityNote:
      "Certification Bed rows are program-specific certified-bed observations, not occupancy and not a unique-facility bed total.",
    adultHomeIsNotEnrichedHousing: true,
    notNursingHome: true,
    credentialRowIsNotFacility: true,
    capacityIsNotOccupancy: true,
  },
  assistedLivingDesignations: {
    coverage: "ACQUIRED_CURRENT_SNAPSHOT",
    alrFacilities: 271,
    ealrFacilities: 220,
    snalrFacilities: 203,
    alpResidentialFacilities: 162,
    alpLhCsaSpecialtyFacilities: 155,
    alpIsNotAlr: true,
    alrIsNotEalr: true,
    alrIsNotSnalr: true,
    doNotSumAsAssistedLivingFacilities: true,
    note: "These are source-native bed/program designations hosted at Adult Homes or Enriched Housing (except LHCSA specialty ALP). One site may carry multiple designations.",
  },
  doNotRefer: {
    coverage: "ACQUIRED_CURRENT_SNAPSHOT",
    source: "NYSDOH Adult Care Facility Do Not Refer List PDF",
    officialUrl: "https://www.health.ny.gov/facilities/adult_care/docs/acf_do_not_refer_list.pdf",
    sourceAsOf: "2026-09-10",
    retrievedAt: "2026-09-11T16:00:00Z",
    observationCount: 117,
    exactOpcertMatchesToCurrentGiAcf: 6,
    nameOnlyRemainder: 111,
    exactProfileAttachments: 0,
    nameOnlyJoins: "UNSAFE",
    namePlusCity: "REVIEW_REQUIRED",
    notCriminalConviction: true,
    notPermanentClosureUnlessSourceSaysClosed: true,
    notEveryEnforcementAction: true,
    notTrustHubBlacklist: true,
    noScore: true,
  },
  homeCare: {
    chhaDistinctFacilityIds: 97,
    lhcsaDistinctFacilityIds: 1258,
    lthhcpDistinctFacilityIds: 30,
    chhaCertificationRows: 1388,
    lhcsaCertificationRows: 15279,
    lhcsaIsNotCmsHha: true,
    chhaIsNotLhcsa: true,
    stateLicenseIsNotCmsCcn: true,
    rowIsNotFacility: true,
  },
  adultDay: {
    coverage: "ACQUIRED_CURRENT_SNAPSHOT",
    adhcpDistinctFacilityIds: 34,
    notAlf: true,
    notNursingHome: true,
  },
  acfInspections: {
    coverage: "PUBLIC_RESEARCH_PATH",
    reason:
      "Health Profiles per-facility ACF inspections. No cheap bulk/API harvested in this ticket.",
  },
  alrQualityTable: {
    coverage: "SOURCE_NOT_ACQUIRED",
    reason: "No deterministic statewide ALR quality bulk table found in this pass.",
  },
  cmsOverlay: {
    nursingHomes: 593,
    homeHealth: 100,
    hospice: 39,
    source: "senior-national-intelligence.json geography NY (CMS class directories)",
    asOf: "2026-08-27",
    nationalFingerprint: "215b9d6301a9759f53dd92324930803089d319f95fe5e46739cbbd5f326c3294",
    addedToNationalTotals: false,
    clocks: {
      nursingHomes: {
        datasetKey: "nursing-home-provider-information",
        officialUrl: "https://data.cms.gov/provider-data/dataset/4pq5-n9py",
        sourceModifiedAt: "2026-08-01T00:00:00+00:00",
        retrievedAt: "2026-08-26T20:24:52.158102+00:00",
        sourcePeriod: null,
      },
      homeHealth: {
        datasetKey: "home-health-care-agencies",
        officialUrl: "https://data.cms.gov/provider-data/dataset/6jpm-sxkc",
        sourceModifiedAt: "2026-05-27T00:00:00+00:00",
        retrievedAt: "2026-08-26T21:08:16.274819+00:00",
        sourcePeriod: null,
      },
      hospice: {
        datasetKey: "hospice-general-information",
        officialUrl: "https://data.cms.gov/provider-data/dataset/yc9t-dgbk",
        sourceModifiedAt: "2026-08-19T00:00:00+00:00",
        retrievedAt: "2026-08-26T22:15:06.243039+00:00",
        sourcePeriod: null,
      },
    },
    stateNhCountIsNotCmsNhCount: true,
    stateHospiceDistinctFacilities: 39,
    stateHospiceExactCmsJoinAttempted: false,
  },
  crosswalk: {
    nyNhToCms: {
      method: "source-native MEDICARE_NUMBER on Nursing Home Profile Facility_Info",
      rowsWithCcn: 595,
      rowsWithoutCcn: 2,
      distinctCcn: 594,
      duplicateCcnValues: 1,
      exact: 594,
    },
    acfToCmsNh: {
      attempted: false,
      exact: 0,
      reviewRequired: 0,
      rejectedUnsafe: 0,
    },
    dnrToGiAcfExactOpcert: 6,
    nameOnlyJoins: "UNSAFE",
  },
  publication: {
    claimableAcfProfiles: false,
    publicAcfProfileRoutes: false,
    stateResearchIdentityIsNotPublicProfile: true,
    noAutomaticNameCmsMatch: true,
    operatorIsNotFacility: true,
    operatorMemberIsNotFacility: true,
  },
  expansionLedger: {
    NY_NURSING_HOME_SOURCE_ROWS: 597,
    NY_NURSING_HOME_STATE_IDENTITIES: 597,
    NY_NURSING_HOME_DISTINCT_CCN: 594,
    NY_NURSING_HOME_INSPECTION_OBSERVATIONS: 6036,
    NY_NURSING_HOME_COMPLAINT_SUMMARY_ROWS: null,
    NY_NURSING_HOME_ENFORCEMENT_FINE_ROWS: 2036,
    NY_ACF_STATE_IDENTITIES: 527,
    NY_ACF_OPERATING_CERTIFICATES: 527,
    NY_ACF_LICENSE_OR_CERTIFICATION_ROWS: 1612,
    NY_ACF_CERTIFIED_CAPACITY: null,
    NY_DO_NOT_REFER_OBSERVATIONS: 117,
    NY_ALR_QUALITY_ROWS: null,
    NY_STATE_HOME_CARE_ROWS: null,
    EXACT_NY_NH_TO_CMS_CROSSWALKS: 594,
    REJECTED_UNSAFE_CROSSWALKS: 0,
    REVIEW_REQUIRED_CROSSWALKS: 0,
    NET_NEW_CANONICAL_FACILITIES: 0,
    NET_NEW_PUBLIC_PROFILES: 0,
    EXACT_PROFILE_ATTACHMENTS: 0,
    EXISTING_ORGANIZATIONS_ENRICHED: 0,
    GRAPH_WRITES: 0,
    notes: {
      complaintSummary:
        "Facility_Info COMP_* fields are source-native complaint-summary columns, not a separate complaint-row census. Citation IS_COMPLAINT=1 is 4,244 citation rows, not complaint filings.",
      acfCapacity:
        "Program-specific Bed measure_value rows exist; they are not a unique-facility occupancy or a single certified-capacity total.",
      homeCare:
        "LHCSA/CHHA/LTHHCP are certification-row classes. Distinct Facility IDs are reported separately and are not CMS HHA.",
    },
  },
  juiceSqueeze: [
    {
      source: "NYSDOH Nursing Home Profile zip",
      decision: "GRABBED \u2014 HIGH YIELD",
      note: "597 facilities, surveys, citations, enforcements, source-native CCN.",
    },
    {
      source: "Health Facility General Information + Certification Information",
      decision: "GRABBED \u2014 HIGH YIELD",
      note: "527 ACF Facility IDs with operating certificates; AH/EHP/AL designations kept separate.",
    },
    {
      source: "Do Not Refer List PDF",
      decision: "GRABBED \u2014 HIGH YIELD",
      note: "117 observations; 6 exact current OPCERT matches; name-only not attached.",
    },
    {
      source: "Existing CMS NY overlays",
      decision: "GRABBED \u2014 HIGH YIELD",
      note: "593 NH / 100 HHA / 39 Hospice. Not added to national totals.",
    },
    {
      source: "LHCSA / CHHA / ADHCP certification distinct Facility IDs",
      decision: "GRABBED \u2014 EASY SECONDARY",
      note: "State home-care and adult-day classes. LHCSA != CMS HHA.",
    },
    {
      source: "ALR quality table",
      decision: "LEFT \u2014 SEARCH ONLY",
      note: "No deterministic bulk table in this pass.",
    },
    {
      source: "Per-facility ACF Health Profiles inspections",
      decision: "LEFT \u2014 TOO MUCH WORK FOR CURRENT YIELD",
      note: "PUBLIC_RESEARCH_PATH.",
    },
    {
      source: "Survey/citation PDFs and operator archaeology",
      decision: "LEFT \u2014 TOO MUCH WORK FOR CURRENT YIELD",
      note: "Bulk CSVs were enough.",
    },
    {
      source: "FOIL",
      decision: "LEFT \u2014 REQUEST ONLY",
      note: "Not requested.",
    },
    {
      source: "NYC / counties / boroughs",
      decision: "LEFT \u2014 LOCAL / FUTURE",
      note: "Statewide only.",
    },
  ],
  claimEligibility: {
    broadened: false,
  },
  noCombinedDenominator: true,
  noTrustScore: true,
  noRanking: true,
  noAggregateRating: true,
  publicationPath: "/new-york",
  noCountyRoutes: true,
  noCityRoutes: true,
  statewideOnly: true,
  unknownIsNotZero: true,
  missingIsNotZero: true,
  searchOnlyIsNotZero: true,
  fingerprint: "0ba069ebbd93faeb3274f3849a34703be2a9ce6fa66289468d6a2dfa5c73af54",
} as const;
