/** Generated by scripts/build-tn-public-snapshot.py. Do not edit by hand. */
export const TN_PUBLIC_SNAPSHOT = {
  "version": "senior-tn-state-intel-v1",
  "ticket": "TN-SEN-001",
  "publicationPath": "/tennessee",
  "asOf": "2026-09-24",
  "snapshotAsOf": "2026-09-24",
  "retrievedAt": "2026-09-24T21:55:44+00:00",
  "generatedAt": "2026-09-24T22:30:00Z",
  "localWorkNeededNow": "NO",
  "claimEligibilityBroadened": false,
  "no_trust_score": true,
  "no_aggregate_rating": true,
  "no_rankings": true,
  "no_city_pages": true,
  "clocks": {
    "generatedAt": "2026-09-24T22:30:00Z",
    "snapshotAsOf": "2026-09-24",
    "hfc_bed_reports_reportMonth": "2026-07",
    "hfc_bed_reports_retrievedAt": "2026-09-24T21:55:44+00:00",
    "hfc_home_health_list_sourceAsOf": "2024-02-07",
    "hfc_hospice_list_sourceAsOf": "2024-03-06",
    "hfc_county_lists_retrievedAt": "2026-09-24T21:55:49+00:00",
    "hfc_actions_window": "2024-01/2026-08",
    "hfc_actions_retrievedAt": "2026-09-24T21:56:48+00:00",
    "cms_nursing_home_sourceAsOf": "2026-08-01T00:00:00+00:00",
    "cms_home_health_sourceAsOf": "2026-05-27T00:00:00+00:00",
    "cms_hospice_sourceAsOf": "2026-08-19T00:00:00+00:00",
    "license_effective_date": null,
    "license_expiration_date": null,
    "retrievedAt_is_not_sourceAsOf": true,
    "report_month_is_not_license_date": true,
    "cms_date_is_not_tennessee_license_date": true
  },
  "regulatorMap": {
    "hfc": "Tennessee Health Facilities Commission (HFC)",
    "consolidation": "The Board for Licensing Health Care Facilities was sunset and its licensing role consolidated into HFC effective July 1, 2024. The archived Board is not a current regulator.",
    "hfcHome": "https://www.tn.gov/hfc.html",
    "healthFacilityReports": "https://www.tn.gov/hfc/publication-and-reports/licensure-reports.html",
    "countyHomeHealthHospice": "https://www.tn.gov/hfc/certificate-of-need-information/hfc-toolbox/county-licensed-home-health-and-hospice-agencies-.html",
    "facilityActions": "https://www.tn.gov/hfc/publication-and-reports/facility-action-and-abuse-reports.html",
    "nursingHomeEnforcement": "https://www.tn.gov/hfc/publication-and-reports/nursing-home-inspection-and-enforcement.html",
    "complaints": "https://www.tn.gov/hfc/division-of-licensure-and-regulation/filing-a-complaint.html",
    "facilityListings": "https://internet.health.tn.gov/FacilityListings",
    "archivedBoard": "https://www.tn.gov/hfc/division-of-licensure-and-regulation/archives--board-for-licensing-health-care-facilities.html",
    "cmsCareCompare": "https://www.medicare.gov/care-compare/"
  },
  "cmsOverlay": {
    "nursingHomes": 303,
    "homeHealth": 128,
    "hospice": 61,
    "source": "senior-national-intelligence.json geography TN (CMS class directories)",
    "asOf": "2026-08-27",
    "nationalFingerprint": "215b9d6301a9759f53dd92324930803089d319f95fe5e46739cbbd5f326c3294",
    "addedToNationalTotals": false,
    "censusConfirmation": {
      "artifact": "artifacts/senior-metric-census-r2-03.json",
      "nursingHomes": 303,
      "homeHealth": 128,
      "hospice": 61
    },
    "clocks": {
      "nursingHomes": {
        "datasetKey": "nursing-home-provider-information",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/4pq5-n9py",
        "sourceModifiedAt": "2026-08-01T00:00:00+00:00",
        "retrievedAt": "2026-08-26T20:24:52.158102+00:00",
        "sourcePeriod": null
      },
      "homeHealth": {
        "datasetKey": "home-health-care-agencies",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/6jpm-sxkc",
        "sourceModifiedAt": "2026-05-27T00:00:00+00:00",
        "retrievedAt": "2026-08-26T21:08:16.274819+00:00",
        "sourcePeriod": null
      },
      "hospice": {
        "datasetKey": "hospice-general-information",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/yc9t-dgbk",
        "sourceModifiedAt": "2026-08-19T00:00:00+00:00",
        "retrievedAt": "2026-08-26T22:15:06.243039+00:00",
        "sourcePeriod": null
      },
      "inspections": {
        "datasetKey": "nursing-home-inspection-dates",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/svdt-c123",
        "sourceModifiedAt": "2026-08-01T00:00:00+00:00",
        "retrievedAt": "2026-08-26T20:18:10.260419+00:00",
        "sourcePeriod": null
      },
      "ownership": {
        "datasetKey": "skilled-nursing-facility-all-owners",
        "officialUrl": "https://data.cms.gov/provider-characteristics/hospitals-and-other-facilities/skilled-nursing-facility-all-owners",
        "sourceModifiedAt": "2026-08-17T00:00:00+00:00",
        "retrievedAt": "2026-08-26T20:25:26.251400+00:00",
        "sourcePeriod": "2026-08-01/2026-08-31"
      },
      "penalties": {
        "datasetKey": "nursing-home-penalties",
        "officialUrl": "https://data.cms.gov/provider-data/dataset/g6vv-u9sr",
        "sourceModifiedAt": "2026-08-01T00:00:00+00:00",
        "retrievedAt": "2026-08-26T20:24:35.184131+00:00",
        "sourcePeriod": null
      }
    }
  },
  "nursingHomes": {
    "reportRows": 327,
    "distinctLicenseNumbers": 326,
    "satelliteRows": 1,
    "satelliteRowsShareLicenseNumber": [
      84
    ],
    "licensedBeds": 36730,
    "bedsSumAllRowsAsListed": 36776,
    "rowsWithBeds": 327,
    "licenseStatusCounts": {
      "Licensed": 305,
      "Licensed - Inactive": 20,
      "On Probation": 1,
      "Closed - Satellite": 1
    },
    "securedBeds": 3821,
    "adultDayCareBeds": 178,
    "facilitiesWithSecuredBeds": 67,
    "outOfStateAddressRows": 0,
    "counties": 95,
    "facilityTypeAsPublished": "Nursing Home",
    "source": "https://www.tn.gov/content/dam/tn/hfc/documents/HFC-Nursing%20Home_Full_Bed_Report_July2026.xlsx",
    "sourceTitle": "Nursing Home Full Bed Report - July 2026",
    "reportMonth": "2026-07",
    "sourceAsOf": "2026-07",
    "sourceAsOfPrecision": "month (the report is titled by month; no day is printed)",
    "retrievedAt": "2026-09-24T21:55:44+00:00",
    "sha256": "6da5081946cf6f201955348d983d72aef85f317c0487c1ec5a66add2dfc9a8d6",
    "columns": [
      "fac_type",
      "lic_no",
      "fac_name",
      "lic_status",
      "street",
      "city",
      "state",
      "zip",
      "county",
      "region",
      "Total_Beds",
      "Does facility have dialysis services?",
      "Does the facility provide bedside dialysis?",
      "Does the facility have a dialysis den?",
      "How many beds for bedside dialysis?",
      "Number of stations in a den:",
      "Vent Beds:",
      "Adult Day Care Services beds:",
      "Secured Beds:",
      "Alzheimer Beds:"
    ],
    "bedGrain": "licensed beds on the HFC report; not residents, not occupancy, not facilities",
    "ccnInSource": false,
    "capability": "KNOWN",
    "distinctFromCmsNursingHome": true,
    "alzheimerBeds": 98,
    "ventBeds": 288,
    "facilitiesWithDialysisServices": 23
  },
  "aclf": {
    "reportRows": 331,
    "distinctLicenseNumbers": 331,
    "satelliteRows": 0,
    "satelliteRowsShareLicenseNumber": [],
    "licensedBeds": 23081,
    "bedsSumAllRowsAsListed": 23081,
    "rowsWithBeds": 331,
    "licenseStatusCounts": {
      "Licensed": 322,
      "On Probation": 2,
      "Licensed On Probation": 1,
      "Licensed - Inactive": 2,
      "Licensed - On Probation": 4
    },
    "securedBeds": 6219,
    "adultDayCareBeds": 225,
    "facilitiesWithSecuredBeds": 198,
    "outOfStateAddressRows": 0,
    "counties": 68,
    "facilityTypeAsPublished": "Assisted Care Living Facility",
    "source": "https://www.tn.gov/content/dam/tn/hfc/documents/HFC-ACLF_Full_Bed_Report_July2026.xlsx",
    "sourceTitle": "Assisted Care Living Facilities Full Bed Report - July 2026",
    "reportMonth": "2026-07",
    "sourceAsOf": "2026-07",
    "sourceAsOfPrecision": "month (the report is titled by month; no day is printed)",
    "retrievedAt": "2026-09-24T21:55:46+00:00",
    "sha256": "4e5afb0d124ccd27eb8d15a1cec8d0d37ce84fc18621578dfdf8321ca0b39ca7",
    "columns": [
      "fac_type",
      "lic_no",
      "fac_name",
      "lic_status",
      "street",
      "city",
      "state",
      "zip",
      "county",
      "region",
      "Total_Beds",
      "Number of Adult Day Care Services beds:",
      "Number of Secured Beds:"
    ],
    "bedGrain": "licensed beds on the HFC report; not residents, not occupancy, not facilities",
    "ccnInSource": false,
    "capability": "KNOWN",
    "credentialName": "Assisted Care Living Facility (ACLF)",
    "consumerExplanation": "Tennessee's licensed assisted-care-living category",
    "distinctFromNursingHome": true,
    "distinctFromRha": true
  },
  "rha": {
    "reportRows": 39,
    "distinctLicenseNumbers": 39,
    "satelliteRows": 0,
    "satelliteRowsShareLicenseNumber": [],
    "licensedBeds": 795,
    "bedsSumAllRowsAsListed": 795,
    "rowsWithBeds": 39,
    "licenseStatusCounts": {
      "Licensed": 39
    },
    "securedBeds": 63,
    "adultDayCareBeds": 23,
    "facilitiesWithSecuredBeds": 2,
    "outOfStateAddressRows": 0,
    "counties": 19,
    "facilityTypeAsPublished": "Home for the Aged",
    "source": "https://www.tn.gov/content/dam/tn/hfc/documents/HFC-Home%20for%20the%20Aged_Full_Bed_Report_July2026.xlsx",
    "sourceTitle": "Residential Home for the Aged Full Bed Report - July 2026",
    "reportMonth": "2026-07",
    "sourceAsOf": "2026-07",
    "sourceAsOfPrecision": "month (the report is titled by month; no day is printed)",
    "retrievedAt": "2026-09-24T21:55:47+00:00",
    "sha256": "a9dcc33b25d59c1d4ba51169a2ee46cf93b652eded180cc0c205c85bf3110f58",
    "columns": [
      "fac_type",
      "lic_no",
      "fac_name",
      "lic_status",
      "street",
      "city",
      "state",
      "zip",
      "county",
      "region",
      "Total_Beds",
      "Secured Beds:",
      "Number of Adult Day Care Services Beds:"
    ],
    "bedGrain": "licensed beds on the HFC report; not residents, not occupancy, not facilities",
    "ccnInSource": false,
    "capability": "KNOWN",
    "credentialName": "Residential Home for the Aged (RHA)",
    "reportTitleUses": "Home for the Aged",
    "distinctFromNursingHome": true,
    "distinctFromAclf": true,
    "distinctFromAdultCareHome": true
  },
  "homeHealth": {
    "countyServiceRows": 2487,
    "distinctAgenciesAsPrinted": 176,
    "distinctStateAgencyIds": null,
    "countiesListed": 95,
    "countiesWithZeroAgencies": 0,
    "statedCountMismatches": [
      {
        "county": "Wilson",
        "statedCount": 42,
        "rowsPrinted": 40
      }
    ],
    "agenciesWithHomeCountyOther": 2,
    "maxCountiesForOneAgency": 95,
    "source": "https://www.tn.gov/content/dam/tn/hfc/documents/HFC-home-health-counties-served.pdf",
    "sourceTitle": "Home Health Agencies In",
    "sourceAsOf": "2024-02-07",
    "sourceDateLabel": "Source: Department of Health Licensure - 2/7/2024",
    "retrievedAt": "2026-09-24T21:55:49+00:00",
    "sha256": "6305ea5315b27cc9444e40bf51d221edf13083783c030ae238f5344181dde22e",
    "grain": "agency (name and home county as printed) x licensed service county",
    "agencyKey": "name and home county exactly as printed (no license number in the list)",
    "agencyIdInSource": false,
    "ccnInSource": false,
    "countyRowsAreNotAgencies": true,
    "distinctFromCmsHomeHealth": true,
    "exemptionLists": {
      "eeoicpa": {
        "countyServiceRows": 755,
        "distinctAgenciesAsPrinted": 25,
        "distinctStateAgencyIds": null,
        "countiesListed": 95,
        "countiesWithZeroAgencies": 0,
        "statedCountMismatches": [],
        "agenciesWithHomeCountyOther": 0,
        "maxCountiesForOneAgency": 95,
        "source": "https://www.tn.gov/content/dam/tn/hfc/documents/HFC-home-health-counties-served-eeoicpa.pdf",
        "sourceTitle": "Home Health Agencies Exempt For EEOICPA In",
        "sourceAsOf": "2024-02-22",
        "sourceDateLabel": "Source: Department of Health Licensure - 2/22/2024",
        "retrievedAt": "2026-09-24T21:55:51+00:00",
        "sha256": "bad6aeeae282898bf78b531f86249b1cbbe9dc31687b7b82addc15604f506449",
        "grain": "agency (name and home county as printed) x licensed service county",
        "agencyKey": "name and home county exactly as printed (no license number in the list)",
        "agencyIdInSource": false,
        "ccnInSource": false,
        "countyRowsAreNotAgencies": true
      },
      "pediatric": {
        "countyServiceRows": 1108,
        "distinctAgenciesAsPrinted": 69,
        "distinctStateAgencyIds": null,
        "countiesListed": 95,
        "countiesWithZeroAgencies": 0,
        "statedCountMismatches": [],
        "agenciesWithHomeCountyOther": 2,
        "maxCountiesForOneAgency": 95,
        "source": "https://www.tn.gov/content/dam/tn/hfc/documents/HFC-home-health-counties-served-pediatric.pdf",
        "sourceTitle": "Home Health Agencies Exempt For Pediatric In",
        "sourceAsOf": "2024-02-22",
        "sourceDateLabel": "Source: Department of Health Licensure - 2/22/2024",
        "retrievedAt": "2026-09-24T21:55:52+00:00",
        "sha256": "fde9048a77a79309f7b73f06416684452eb8e990ea628af26989c72c86fcea03",
        "grain": "agency (name and home county as printed) x licensed service county",
        "agencyKey": "name and home county exactly as printed (no license number in the list)",
        "agencyIdInSource": false,
        "ccnInSource": false,
        "countyRowsAreNotAgencies": true
      }
    },
    "exemptionListsAddedToMainList": false,
    "capability": "PARTIAL",
    "capabilityReason": "Official HFC list, but its printed source date is early 2024 (Department of Health licensure data), and it has no agency license number."
  },
  "hospice": {
    "countyServiceRows": 732,
    "distinctAgenciesAsPrinted": 63,
    "distinctStateAgencyIds": null,
    "countiesListed": 95,
    "countiesWithZeroAgencies": 0,
    "statedCountMismatches": [
      {
        "county": "Campbell",
        "statedCount": 9,
        "rowsPrinted": 8
      },
      {
        "county": "Humphreys",
        "statedCount": 7,
        "rowsPrinted": 8
      },
      {
        "county": "Wilson",
        "statedCount": 11,
        "rowsPrinted": 10
      }
    ],
    "agenciesWithHomeCountyOther": 1,
    "maxCountiesForOneAgency": 89,
    "source": "https://www.tn.gov/content/dam/tn/hfc/documents/HFC-hospice-counties-served.pdf",
    "sourceTitle": "Hospice Agencies In",
    "sourceAsOf": "2024-03-06",
    "sourceDateLabel": "Source: Department of Health Licensure - 3/6/2024",
    "retrievedAt": "2026-09-24T21:55:54+00:00",
    "sha256": "731e981c04679b4414c88e58a72c25c41b6d1fc29e2efb61fbafffa738e8e8c0",
    "grain": "agency (name and home county as printed) x licensed service county",
    "agencyKey": "name and home county exactly as printed (no license number in the list)",
    "agencyIdInSource": false,
    "ccnInSource": false,
    "countyRowsAreNotAgencies": true,
    "distinctFromCmsHospice": true,
    "capability": "PARTIAL",
    "capabilityReason": "Official HFC list, but its printed source date is early 2024 (Department of Health licensure data), and it has no agency license number."
  },
  "adultCareHome": {
    "rosterRows": null,
    "capability": "NOT_ACQUIRED",
    "reason": "HFC publishes no Adult Care Home report on the Health Facility Reports page. Adult Care Home is not mapped into RHA or ACLF.",
    "actionRows": 1
  },
  "facilityActions": {
    "source": "https://www.tn.gov/hfc/publication-and-reports/facility-action-and-abuse-reports.html",
    "window": "2024-01/2026-08",
    "sourceAsOf": "2026-08",
    "retrievedAt": "2026-09-24T21:56:48+00:00",
    "monthsAcquired": 31,
    "monthsMissingFromArchive": [
      "2026-01"
    ],
    "seniorClassActionRows": 201,
    "byCareSetting": {
      "aclf": 129,
      "adultCareHome": 1,
      "homeHealth": 1,
      "nursingHomes": 67,
      "rha": 3
    },
    "byLicenseClassAsPrinted": {
      "A.C.H.": 1,
      "A.C.L.F.": 129,
      "H.H.A.": 1,
      "N.H.": 39,
      "R.H.A.": 3,
      "S.N.F.": 28
    },
    "byOrderSection": {
      "BOARD ORDERS": 153,
      "COMMISSION CONDITIONAL CHOW ORDERS": 1,
      "COMMISSION ORDERS": 8,
      "EXECUTIVE DIRECTOR ORDERS": 39
    },
    "byAttribution": {
      "attached_exact_license_number_and_name_agrees": 163,
      "standalone_license_number_found_but_name_differs": 24,
      "standalone_license_number_not_on_july_2026_report": 12,
      "standalone_no_state_roster_for_class": 2
    },
    "attachedToStateReportRow": 163,
    "withCivilMonetaryPenalty": 187,
    "withProbation": 21,
    "withSuspensionOrRevocationLanguage": 10,
    "cmpAmountParsedRows": 186,
    "otherClassActionsNotPublished": {
      "A.S.T.C.": 2,
      "H.M.E.": 1,
      "Hospital": 2,
      "T.S.A.": 6,
      "T.S.R.": 2
    },
    "abuseRegistryEntries": 418,
    "abuseRegistryNamesPublished": false,
    "abuseRegistryIsPersonLevel": true,
    "attachmentRule": "exact license class + license number on the July 2026 HFC report, and the printed name agrees after normalization; otherwise standalone",
    "attachedToCmsProfile": 0,
    "nameOnlyJoins": 0,
    "capability": "PARTIAL"
  },
  "nursingHomeEnforcementReport": {
    "source": "https://www.tn.gov/content/dam/tn/hfc/documents/Annual%20Nursing%20Home%20Inspection%20and%20Enforcement%20Report-2025.pdf",
    "title": "Annual Nursing Home Inspection and Enforcement Report 2025 (Report to the 114th General Assembly, February 2025)",
    "pages": 15,
    "statedNursingHomesOperating2024": 308,
    "statedCmsCertified2024": 304,
    "facilityLevelRowsTaken": 0,
    "usedAsIdentitySource": false,
    "capability": "KNOWN",
    "note": "Narrative and aggregate tables; context only. Facility-level inspection evidence stays on CMS profiles."
  },
  "complaints": {
    "intake": "KNOWN",
    "portal": "HFC Public Records and Complaints portal (GovQA)",
    "providerLevelRows": null,
    "outcomeBulk": "NOT_ACQUIRED",
    "capability": "REQUEST_ONLY",
    "complaintIsNotDeficiency": true,
    "complaintIsNotEnforcement": true
  },
  "facilityListings": {
    "url": "https://internet.health.tn.gov/FacilityListings",
    "capability": "KNOWN",
    "bulkCapability": "NOT_ACQUIRED",
    "reason": "Interactive search; it refused automated access (HTTP 403) and was not scraped. Use it to verify a facility."
  },
  "closures": {
    "rows": null,
    "capability": "NOT_ACQUIRED",
    "reason": "Closed-facility lists appear only inside Commission meeting materials; deferred."
  },
  "certificateOfNeed": {
    "usedAsIdentity": false,
    "note": "CON applications are not licensed operating facilities."
  },
  "cmsMoratorium": {
    "source": "https://www.cms.gov/files/document/qso-26-11-hha-hospice-original-release-2026-05-20.pdf",
    "note": "CMS set a six-month nationwide moratorium starting May 20, 2026 on initial Medicare enrollment of new Home Health Agencies and hospices. It is a federal enrollment rule, not a Tennessee license suspension."
  },
  "crosswalk": {
    "exactStateToCmsBridges": 0,
    "attempted": true,
    "method": "exact CCN in state source",
    "ccnInHfcReports": false,
    "ccnInCountyLists": false,
    "nameOnly": "UNSAFE",
    "hfcNursingHomeRowsUnresolved": 327,
    "cmsNursingHomeRowsUnresolved": 303,
    "capability": "UNKNOWN",
    "reason": "The HFC reports have no CCN, so no exact bridge exists. Zero proven exact bridges does not mean zero overlap: HFC's own 2025 report says most licensed nursing homes are CMS-certified, but which row is which is not established here."
  },
  "cityContext": {
    "grain": "HFC report rows with that city in the source address; Home Health and Hospice use the county list for the city's county. Not a local page.",
    "cities": {
      "Nashville": {
        "nursingHomes": 14,
        "aclf": 18,
        "rha": 4,
        "county": "Davidson",
        "homeHealthAgenciesLicensedForCounty": 42,
        "hospiceAgenciesLicensedForCounty": 17
      },
      "Memphis": {
        "nursingHomes": 19,
        "aclf": 14,
        "rha": 3,
        "county": "Shelby",
        "homeHealthAgenciesLicensedForCounty": 33,
        "hospiceAgenciesLicensedForCounty": 9
      },
      "Knoxville": {
        "nursingHomes": 15,
        "aclf": 27,
        "rha": 3,
        "county": "Knox",
        "homeHealthAgenciesLicensedForCounty": 32,
        "hospiceAgenciesLicensedForCounty": 11
      },
      "Chattanooga": {
        "nursingHomes": 6,
        "aclf": 12,
        "rha": 5,
        "county": "Hamilton",
        "homeHealthAgenciesLicensedForCounty": 27,
        "hospiceAgenciesLicensedForCounty": 9
      }
    }
  },
  "expansionLedger": {
    "NET_NEW_STATE_RESEARCH_IDENTITIES": 697,
    "NET_NEW_CANONICAL_FACILITIES": 0,
    "NET_NEW_PUBLIC_PROFILES": 0,
    "EXISTING_FACILITIES_ENRICHED": 0,
    "GRAPH_WRITES": 0,
    "CLAIM_ELIGIBILITY_BROADENED": false
  },
  "capabilities": [
    {
      "id": "cms-nursing-home-tn",
      "state": "KNOWN"
    },
    {
      "id": "cms-home-health-tn",
      "state": "KNOWN"
    },
    {
      "id": "cms-hospice-tn",
      "state": "KNOWN"
    },
    {
      "id": "hfc-nursing-home-report-july-2026",
      "state": "KNOWN"
    },
    {
      "id": "hfc-aclf-report-july-2026",
      "state": "KNOWN"
    },
    {
      "id": "hfc-rha-report-july-2026",
      "state": "KNOWN"
    },
    {
      "id": "hfc-home-health-county-list",
      "state": "PARTIAL"
    },
    {
      "id": "hfc-hospice-county-list",
      "state": "PARTIAL"
    },
    {
      "id": "hfc-home-health-hospice-license-numbers",
      "state": "UNKNOWN"
    },
    {
      "id": "adult-care-home-roster",
      "state": "NOT_ACQUIRED"
    },
    {
      "id": "hfc-facility-actions-2024-2026",
      "state": "PARTIAL"
    },
    {
      "id": "hfc-nursing-home-enforcement-report-2025",
      "state": "KNOWN"
    },
    {
      "id": "hfc-complaint-intake",
      "state": "KNOWN"
    },
    {
      "id": "hfc-provider-complaints",
      "state": "REQUEST_ONLY"
    },
    {
      "id": "hfc-facility-listings-bulk",
      "state": "NOT_ACQUIRED"
    },
    {
      "id": "closed-facility-list",
      "state": "NOT_ACQUIRED"
    },
    {
      "id": "exact-state-to-cms-join",
      "state": "UNKNOWN"
    },
    {
      "id": "name-only-state-to-cms-join",
      "state": "UNSUPPORTED"
    },
    {
      "id": "combined-tennessee-senior-facilities",
      "state": "UNSUPPORTED"
    },
    {
      "id": "combined-tennessee-senior-beds",
      "state": "UNSUPPORTED"
    }
  ],
  "fingerprint": "f95d81b37f042879e0259bf8d833e0e89122e8a44e55030aa281ca044b047ea9"
} as const;
export type TnPublicSnapshot = typeof TN_PUBLIC_SNAPSHOT;
