"""National Senior Intelligence metric contract. No combined senior-provider denominator."""

from __future__ import annotations

SNAPSHOT_VERSION = "senior-national-intel-v1"
METRIC_VERSION = "v1"
TRANSFORMATION_VERSION = "senior-intel-v1"

NEVER_COMBINE_PROVIDER_CLASSES = True
MISSING_QUALITY_IS_NOT_ZERO = True
UNKNOWN_IS_NOT_FORMER_OWNER = True


def combined_senior_provider_denominator_allowed() -> bool:
    return False


def zip_is_county_service_area() -> bool:
    return False


def pac_is_parent_company() -> bool:
    return False


def chow_is_quality_or_stability_score() -> bool:
    return False


def unknown_counts_as_historical() -> bool:
    return False


def fingerprint_includes_generated_at() -> bool:
    return False


def metric(
    key: str,
    *,
    display: str,
    provider_type: str,
    family: str,
    entity: str,
    definition: str,
    derivation: str,
    sources: tuple[str, ...],
    grain: str,
    freshness: str,
    computability: str,
    publication: str,
    safe: str,
    unsafe: str,
    limitations: str,
    numerator: str | None = None,
    denominator: str | None = None,
) -> dict[str, object]:
    return {
        "metric_key": key,
        "metric_version": METRIC_VERSION,
        "display_name": display,
        "provider_type": provider_type,
        "evidence_family": family,
        "entity_class": entity,
        "definition": definition,
        "numerator_definition": numerator,
        "denominator_definition": denominator,
        "derivation": derivation,
        "source_datasets": list(sources),
        "geography_grain": grain,
        "freshness_rule": freshness,
        "computability_status": computability,
        "publication_status": publication,
        "language_safe": safe,
        "language_unsafe": unsafe,
        "limitations": limitations,
    }


METRICS: tuple[dict[str, object], ...] = (
    metric(
        "nh_current",
        display="Current CMS nursing homes",
        provider_type="nursing_home",
        family="directory",
        entity="PROVIDER",
        definition="Latest Provider Information directory status CURRENT_ACTIVE, distinct CCN.",
        derivation="DIRECT",
        sources=("nursing-home-provider-information",),
        grain="national",
        freshness="cms_source_freshness for nursing-home-provider-information",
        computability="COMPUTABLE",
        publication="PUBLIC_READY",
        safe="14,690 current CMS nursing homes",
        unsafe="14,690 senior facilities",
        limitations="Current-directory membership only. Missing from PI is not closure.",
        denominator="Current CMS nursing-home directory",
    ),
    metric(
        "nh_known",
        display="Known nursing-home CCNs",
        provider_type="nursing_home",
        family="directory",
        entity="PROVIDER",
        definition="Typed nursing_home providers regardless of current-directory status.",
        derivation="DIRECT",
        sources=("nursing-home-provider-information",),
        grain="national",
        freshness="directory + historical CCN identity",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="14,696 known nursing-home CCNs in SeniorTrustHub",
        unsafe="14,696 current nursing homes",
        limitations="Includes facilities absent from the current PI directory.",
    ),
    metric(
        "hh_current",
        display="Current CMS home health agencies",
        provider_type="home_health",
        family="directory",
        entity="PROVIDER",
        definition="Home health snapshot rows in the current CMS agency directory.",
        derivation="DIRECT",
        sources=("home-health-care-agencies",),
        grain="national",
        freshness="cms_source_freshness for home-health-care-agencies",
        computability="COMPUTABLE",
        publication="PUBLIC_READY",
        safe="12,460 current CMS home health agencies",
        unsafe="12,460 senior facilities",
        limitations="Office location is not a service-area claim.",
    ),
    metric(
        "hospice_current",
        display="Current CMS hospice providers (GI directory)",
        provider_type="hospice",
        family="directory",
        entity="PROVIDER",
        definition="Hospice General Information snapshot rows. Not typed quality-only CCNs.",
        derivation="DIRECT",
        sources=("hospice-general-information",),
        grain="national",
        freshness="cms_source_freshness for hospice-general-information",
        computability="COMPUTABLE",
        publication="PUBLIC_READY",
        safe="6,669 current CMS hospice providers",
        unsafe="6,911 current hospice providers",
        limitations="Quality-only CCNs are excluded from this denominator.",
    ),
    metric(
        "hospice_typed_identities",
        display="Typed hospice provider identities",
        provider_type="hospice",
        family="directory",
        entity="PROVIDER",
        definition="All providers typed hospice, including quality-only CCNs.",
        derivation="DIRECT",
        sources=("hospice-general-information", "hospice-provider-data"),
        grain="national",
        freshness="mixed hospice sources",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="6,911 typed hospice identities, of which 6,669 are current GI directory",
        unsafe="6,911 current hospice providers",
        limitations="242 quality-only CCNs are not current-directory providers.",
    ),
    metric(
        "hospice_quality_only_non_directory",
        display="Hospice quality-only CCNs outside current directory",
        provider_type="hospice",
        family="directory",
        entity="PROVIDER",
        definition="Typed hospice providers minus GI directory.",
        derivation="DERIVED",
        sources=("hospice-general-information", "hospice-provider-data"),
        grain="national",
        freshness="mixed hospice sources",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="242 hospice CCNs appear in quality files but not the current GI directory",
        unsafe="242 additional current hospice providers",
        limitations="Do not promote these CCNs into the current-directory count.",
        numerator="Typed hospice minus GI directory",
        denominator="Typed hospice identities",
    ),
    metric(
        "combined_cms_senior_providers",
        display="Combined CMS senior providers",
        provider_type="national",
        family="directory",
        entity="NONE",
        definition="Intentionally not computed. Classes stay separate.",
        derivation="DERIVED",
        sources=(),
        grain="national",
        freshness="n/a",
        computability="UNSUPPORTED",
        publication="DO_NOT_PUBLISH",
        safe="Do not combine nursing home, home health, and hospice directories",
        unsafe="33,819 senior facilities in America",
        limitations="Different CMS datasets and identities. Default rule: DO NOT COMBINE.",
    ),
    metric(
        "assisted_living_cms_national_count",
        display="National CMS assisted living count",
        provider_type="assisted_living",
        family="directory",
        entity="NONE",
        definition="Assisted Living is state-regulated. No CMS national directory.",
        derivation="DIRECT",
        sources=(),
        grain="national",
        freshness="n/a",
        computability="UNSUPPORTED",
        publication="DO_NOT_PUBLISH",
        safe="Assisted Living coverage is state-by-state, not a CMS national count",
        unsafe="National assisted living total from CMS",
        limitations="STATE-DEPENDENT PROVIDER CLASS. Not in the CMS national graph.",
    ),
    metric(
        "memory_care_cms_national_count",
        display="National CMS memory care count",
        provider_type="memory_care",
        family="directory",
        entity="NONE",
        definition="Memory Care is not a CMS national provider class.",
        derivation="DIRECT",
        sources=(),
        grain="national",
        freshness="n/a",
        computability="UNSUPPORTED",
        publication="DO_NOT_PUBLISH",
        safe="Memory Care is not counted as a CMS national provider class",
        unsafe="National memory care total from CMS",
        limitations="STATE-DEPENDENT. Do not invent a CMS national count.",
    ),
    metric(
        "cms_provider_types_researched",
        display="CMS provider types in the national graph",
        provider_type="national",
        family="directory",
        entity="NONE",
        definition="Count of first-class CMS classes with current directories: NH, HH, Hospice.",
        derivation="DIRECT",
        sources=(
            "nursing-home-provider-information",
            "home-health-care-agencies",
            "hospice-general-information",
        ),
        grain="national",
        freshness="per-source",
        computability="COMPUTABLE",
        publication="PUBLIC_READY",
        safe=(
            "SeniorTrustHub researches three CMS provider types: "
            "nursing homes, home health, and hospice"
        ),
        unsafe="All senior care in America",
        limitations="Does not include Assisted Living or Memory Care.",
    ),
    metric(
        "nh_chow_events",
        display="CMS SNF CHOW events",
        provider_type="nursing_home",
        family="ownership_change",
        entity="EVENT",
        definition="Rows in ownership_change_event from SNF CHOW. Not sales or quality.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-change-of-ownership",),
        grain="national",
        freshness="cms_source_freshness for SNF CHOW",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="CMS has published 5,227 skilled nursing ownership-change records",
        unsafe="5,227 nursing home sales",
        limitations="CH vs AM preserved. Event count is not a provider count.",
    ),
    metric(
        "nh_chow_history_providers",
        display="Nursing homes with CMS ownership-change history",
        provider_type="nursing_home",
        family="ownership_change",
        entity="PROVIDER",
        definition="Distinct providers with ≥1 attached confirmed CHOW event.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-change-of-ownership",),
        grain="national",
        freshness="SNF CHOW effective dates; not snapshot recency",
        computability="COMPUTABLE",
        publication="CONDITIONAL",
        safe="CMS records show ownership-change history for X nursing homes",
        unsafe="X nursing homes have unstable ownership",
        limitations="Requires an attached event. HISTORICAL/UNKNOWN edges do not qualify.",
        numerator="Providers with ≥1 attached CHOW event",
        denominator="Current CMS nursing-home directory is a separate metric",
    ),
    metric(
        "hh_chow_history_providers",
        display="Home health CMS CHOW history",
        provider_type="home_health",
        family="ownership_change",
        entity="NONE",
        definition="No public CMS CHOW event source for Home Health.",
        derivation="DIRECT",
        sources=(),
        grain="national",
        freshness="n/a",
        computability="UNSUPPORTED",
        publication="DO_NOT_PUBLISH",
        safe="CMS does not publish a Home Health ownership-change event file",
        unsafe="Home health agencies with ownership-change history",
        limitations="Do not infer events from All Owners snapshot differences.",
    ),
    metric(
        "hospice_chow_history_providers",
        display="Hospice CMS CHOW history",
        provider_type="hospice",
        family="ownership_change",
        entity="NONE",
        definition="No public CMS CHOW event source for Hospice.",
        derivation="DIRECT",
        sources=(),
        grain="national",
        freshness="n/a",
        computability="UNSUPPORTED",
        publication="DO_NOT_PUBLISH",
        safe="CMS does not publish a Hospice ownership-change event file",
        unsafe="Hospice providers with ownership-change history",
        limitations="Do not infer events from All Owners snapshot differences.",
    ),
    metric(
        "unresolved_provider_org_edges",
        display="Unresolved provider-organization edges",
        provider_type="national",
        family="ownership",
        entity="OBSERVATION",
        definition="Graph edges with no provider_id. Excluded from confirmed provider metrics.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-all-owners",),
        grain="national",
        freshness="ownership graph transformation",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="117,192 ownership-graph rows are not linked to a provider",
        unsafe="117,192 providers with unknown owners",
        limitations="Observation count, not a provider count.",
    ),
    metric(
        "canonical_organizations",
        display="Canonical organizations",
        provider_type="organization",
        family="ownership",
        entity="ORGANIZATION",
        definition="organization.id count. Not a provider count. PAC is not parent company.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-enrollments",),
        grain="national",
        freshness="ownership graph",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="205,082 canonical organization identities in the research graph",
        unsafe="205,082 senior providers",
        limitations="Entity class is ORGANIZATION, not PROVIDER.",
    ),
    metric(
        "nh_quality_combined_score",
        display="Combined cross-class quality score",
        provider_type="national",
        family="quality",
        entity="NONE",
        definition="Not computed. NH, HH, and Hospice quality families stay separate.",
        derivation="DERIVED",
        sources=(),
        grain="national",
        freshness="n/a",
        computability="UNSUPPORTED",
        publication="DO_NOT_PUBLISH",
        safe="Quality evidence remains provider-type specific",
        unsafe="National senior quality score",
        limitations="Do not average NH stars, HH quality, and Hospice QRP.",
    ),
    metric(
        "nh_mds_quality_coverage",
        display="Nursing homes with MDS quality observations",
        provider_type="nursing_home",
        family="mds",
        entity="PROVIDER",
        definition=(
            "Current-directory NH with ≥1 MDS quality observation. Missing is not a zero score."
        ),
        derivation="DERIVED",
        sources=("nursing-home-mds-quality-measures",),
        grain="national",
        freshness="cms_source_freshness for MDS",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="X of Y current nursing homes have MDS quality observations",
        unsafe="Y minus X nursing homes have poor quality",
        limitations="Coverage, not a quality score. Missing evidence is not zero.",
        numerator="Current NH with ≥1 MDS observation",
        denominator="Current CMS nursing-home directory",
    ),
    metric(
        "hh_quality_coverage",
        display="Home health agencies with quality observations",
        provider_type="home_health",
        family="hh_quality",
        entity="PROVIDER",
        definition="Current HH with ≥1 hh_quality observation.",
        derivation="DERIVED",
        sources=("home-health-care-agencies",),
        grain="national",
        freshness="per HH quality source",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="X of 12,460 current home health agencies have quality observations",
        unsafe="Agencies without observations have quality zero",
        limitations="HHCAHPS is a separate family.",
        numerator="Current HH with hh_quality rows",
        denominator="Current CMS home health directory",
    ),
    metric(
        "hh_hhcahps_coverage",
        display="Home health agencies with HHCAHPS observations",
        provider_type="home_health",
        family="hh_hhcahps",
        entity="PROVIDER",
        definition="Current HH with ≥1 HHCAHPS observation. Not combined with Hospice CAHPS.",
        derivation="DERIVED",
        sources=("home-health-patient-survey-hhcahps",),
        grain="national",
        freshness="per HHCAHPS source",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="X of 12,460 current home health agencies have HHCAHPS observations",
        unsafe="National patient-experience score across HH and hospice",
        limitations="Survey family stays separate from hospice CAHPS.",
        numerator="Current HH with HHCAHPS rows",
        denominator="Current CMS home health directory",
    ),
    metric(
        "hospice_qrp_coverage",
        display="Hospice GI directory with QRP observations",
        provider_type="hospice",
        family="hospice_quality",
        entity="PROVIDER",
        definition="Current GI hospice with ≥1 hospice_quality observation.",
        derivation="DERIVED",
        sources=("hospice-provider-data",),
        grain="national",
        freshness="per hospice quality source",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="X of 6,669 current hospice providers have QRP observations",
        unsafe="Hospice quality-only CCNs are current providers",
        limitations="Denominator is GI directory, not typed 6,911.",
        numerator="GI hospice with hospice_quality rows",
        denominator="Current CMS hospice GI directory",
    ),
    metric(
        "hospice_cahps_coverage",
        display="Hospice GI directory with CAHPS observations",
        provider_type="hospice",
        family="hospice_cahps",
        entity="PROVIDER",
        definition="Current GI hospice with ≥1 hospice_cahps observation.",
        derivation="DERIVED",
        sources=("hospice-provider-cahps",),
        grain="national",
        freshness="per hospice CAHPS source",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="X of 6,669 current hospice providers have CAHPS observations",
        unsafe="Combined HHCAHPS and Hospice CAHPS score",
        limitations="Not combined with HHCAHPS.",
        numerator="GI hospice with hospice_cahps rows",
        denominator="Current CMS hospice GI directory",
    ),
    metric(
        "owned_by_providers_by_class",
        display="Providers with ≥1 resolved OWNED_BY edge",
        provider_type="national",
        family="ownership",
        entity="PROVIDER",
        definition="Distinct provider_id by class on OWNED_BY. Excludes unresolved edges.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-all-owners",),
        grain="national",
        freshness="ownership graph",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="Resolved CMS/PECOS ownership relationships by provider class",
        unsafe="1.4 million ownership findings",
        limitations="Unresolved provider_id edges excluded. OWNED_BY ≠ OPERATED_BY.",
    ),
    metric(
        "cross_class_organizations",
        display="Canonical organizations by CMS provider-class mix",
        provider_type="organization",
        family="ownership",
        entity="ORGANIZATION",
        definition="Canonical organization_id connected to resolved providers, by class mix.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-all-owners",),
        grain="national",
        freshness="ownership graph",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe=(
            "CMS/PECOS evidence connects this organization to providers "
            "across multiple CMS provider types"
        ),
        unsafe="This company owns all these providers / PAC is the parent company",
        limitations="PAC is PECOS identity, not parent company. Denominator is organizations.",
    ),
    metric(
        "owner_network_size",
        display="Owner-organization network size buckets",
        provider_type="organization",
        family="ownership",
        entity="ORGANIZATION",
        definition="Distinct resolved providers per organization on OWNED_BY only.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-all-owners",),
        grain="national",
        freshness="ownership graph",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="Distribution of how many providers an owner organization is connected to",
        unsafe="Largest or best chains",
        limitations="Size buckets only. Not a ranking.",
    ),
    metric(
        "org_multi_state_office_footprint",
        display="Organization multi-state office footprint",
        provider_type="organization",
        family="geography",
        entity="ORGANIZATION",
        definition=(
            "Distinct office state_code of resolved connected providers. Not ZIP service area."
        ),
        derivation="DIRECT",
        sources=("nursing-home-provider-information",),
        grain="state",
        freshness="directory snapshots",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="Organization office-state footprint across connected providers",
        unsafe="Multi-state service area",
        limitations="Office geography, not county service.",
    ),
    metric(
        "source_freshness_bands",
        display="CMS source freshness bands",
        provider_type="national",
        family="freshness",
        entity="SOURCE",
        definition="Counts of cms_source_freshness rows by CURRENT/AGING/STALE/UNKNOWN.",
        derivation="DIRECT",
        sources=("cms_source_freshness",),
        grain="national",
        freshness="per-source SLA; not a global last-updated clock",
        computability="COMPUTABLE",
        publication="CONDITIONAL",
        safe="Source-specific freshness status from the CMS refresh registry",
        unsafe="SeniorTrustHub last updated [one timestamp]",
        limitations="generated_at of this snapshot is not evidence freshness.",
    ),
    metric(
        "nh_chow_events_by_year",
        display="SNF CHOW events by effective year",
        provider_type="nursing_home",
        family="ownership_change",
        entity="EVENT",
        definition="Event counts grouped by CMS effective_date year.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-change-of-ownership",),
        grain="national",
        freshness="CHOW effective dates",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="CMS ownership-change records by effective year",
        unsafe="Ownership turnover rate by year",
        limitations="Event denominator, not provider denominator.",
    ),
    metric(
        "nh_chow_repeat_providers",
        display="Nursing homes by confirmed CHOW event count",
        provider_type="nursing_home",
        family="ownership_change",
        entity="PROVIDER",
        definition="Providers with 1 / 2 / 3–5 / 6+ attached CHOW events.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-change-of-ownership",),
        grain="national",
        freshness="CHOW effective dates",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="How many nursing homes have 1, 2, or more CMS ownership-change records",
        unsafe="Frequent-sale or unstable-ownership ranking",
        limitations="Structural history only. Not a quality metric.",
    ),
    metric(
        "nh_evidence_coverage",
        display="Nursing home evidence coverage (current directory)",
        provider_type="nursing_home",
        family="coverage",
        entity="PROVIDER",
        definition=(
            "Current NH with MDS, PBJ, fire, inspection, SFF, OWNED_BY, operator, management, CHOW."
        ),
        derivation="DERIVED",
        sources=("nursing-home-mds-quality-measures",),
        grain="national",
        freshness="per evidence family",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="Research coverage of current nursing homes by evidence family",
        unsafe="Nursing homes without a file have quality zero",
        limitations="Coverage counts, not scores. Families stay separate.",
        numerator="Current NH with each evidence family (see snapshot JSON)",
        denominator="Current CMS nursing-home directory",
    ),
    metric(
        "hh_evidence_coverage",
        display="Home health evidence coverage",
        provider_type="home_health",
        family="coverage",
        entity="PROVIDER",
        definition=(
            "Current HH with quality, HHCAHPS, enrollment, OWNED_BY, operator/management, ZIP."
        ),
        derivation="DERIVED",
        sources=("home-health-care-agencies",),
        grain="national",
        freshness="per evidence family",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="Research coverage of current home health agencies by evidence family",
        unsafe="Home health ownership-change history",
        limitations="No CHOW metric. ZIP is not county service.",
        numerator="Current HH with each evidence family (see snapshot JSON)",
        denominator="Current CMS home health directory",
    ),
    metric(
        "hospice_evidence_coverage",
        display="Hospice GI evidence coverage",
        provider_type="hospice",
        family="coverage",
        entity="PROVIDER",
        definition="GI hospice with QRP, CAHPS, enrollment, OWNED_BY, operator/management, ZIP.",
        derivation="DERIVED",
        sources=("hospice-general-information",),
        grain="national",
        freshness="per evidence family",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="Research coverage of current hospice providers by evidence family",
        unsafe="6,911 current hospice providers",
        limitations="Denominator is GI 6,669. No CHOW metric.",
        numerator="GI hospice with each evidence family (see snapshot JSON)",
        denominator="Current CMS hospice GI directory",
    ),
    metric(
        "provider_office_states",
        display="Office states/territories by provider class",
        provider_type="national",
        family="geography",
        entity="PROVIDER",
        definition="Distinct office state_code counts per class. Not combined. Not ZIP service.",
        derivation="DIRECT",
        sources=("nursing-home-provider-information",),
        grain="state",
        freshness="directory snapshots",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="Current providers by office state, separately for NH, HH, and hospice",
        unsafe="Senior providers by state",
        limitations="Office location. No State Intelligence pages.",
    ),
    metric(
        "unknown_ownership_edges",
        display="UNKNOWN ownership-graph edges",
        provider_type="national",
        family="ownership",
        entity="OBSERVATION",
        definition="Edges with temporal_status UNKNOWN. Not former owners.",
        derivation="DIRECT",
        sources=("skilled-nursing-facility-all-owners",),
        grain="national",
        freshness="ownership graph",
        computability="COMPUTABLE",
        publication="INTERNAL_ONLY",
        safe="Ownership relationships observed only in older snapshots remain UNKNOWN",
        unsafe="Former owners / divested owners",
        limitations="UNKNOWN ≠ HISTORICAL ≠ DIVESTED.",
    ),
    metric(
        "county_service_area_providers",
        display="Providers with verified county service area",
        provider_type="national",
        family="geography",
        entity="NONE",
        definition="County service area is not established from ZIP coverage.",
        derivation="DIRECT",
        sources=("home-health-zip-codes", "hospice-zip-data"),
        grain="county",
        freshness="n/a",
        computability="UNSUPPORTED",
        publication="DO_NOT_PUBLISH",
        safe="CMS ZIP coverage records are not a verified county service area",
        unsafe="Providers serving this county",
        limitations="Office geography ≠ ZIP evidence ≠ service area.",
    ),
)

LIMITATIONS: tuple[dict[str, str], ...] = (
    {
        "limitation_key": "classes_are_separate",
        "title": "Provider classes stay separate",
        "body": (
            "Nursing homes, home-health agencies, and hospice providers are regulated "
            "and reported through different CMS datasets."
        ),
        "provider_type": "national",
        "publication_status": "PUBLIC_READY",
    },
    {
        "limitation_key": "al_mc_state_dependent",
        "title": "Assisted Living and Memory Care are state-dependent",
        "body": (
            "Assisted Living and Memory Care are primarily state-regulated, so national "
            "CMS counts do not represent those markets."
        ),
        "provider_type": "assisted_living",
        "publication_status": "PUBLIC_READY",
    },
    {
        "limitation_key": "ownership_is_not_quality",
        "title": "Ownership evidence is not quality",
        "body": "Ownership evidence does not by itself measure quality.",
        "provider_type": "national",
        "publication_status": "PUBLIC_READY",
    },
    {
        "limitation_key": "zip_is_not_service_area",
        "title": "ZIP coverage is not county service area",
        "body": ("CMS ZIP coverage records are not the same as a verified county service area."),
        "provider_type": "national",
        "publication_status": "PUBLIC_READY",
    },
    {
        "limitation_key": "unknown_is_not_divestiture",
        "title": "UNKNOWN is not historical ownership",
        "body": (
            "An ownership relationship observed only in an older snapshot is UNKNOWN, "
            "not a former owner or confirmed divestiture."
        ),
        "provider_type": "nursing_home",
        "publication_status": "INTERNAL_ONLY",
    },
    {
        "limitation_key": "hh_hospice_no_chow",
        "title": "No public HH or Hospice CHOW file",
        "body": (
            "CMS does not publish an explicit Home Health or Hospice change-of-ownership "
            "event file. Snapshot differences are not events."
        ),
        "provider_type": "national",
        "publication_status": "INTERNAL_ONLY",
    },
    {
        "limitation_key": "no_combined_quality",
        "title": "No blended senior quality score",
        "body": (
            "Nursing home, home health, and hospice quality families are not averaged "
            "or ranked against each other."
        ),
        "provider_type": "national",
        "publication_status": "PUBLIC_READY",
    },
)

TOPLINES: dict[str, str] = {
    "Current CMS Nursing Homes": "PUBLIC_READY",
    "Current CMS Home Health Agencies": "PUBLIC_READY",
    "Current CMS Hospice Providers": "PUBLIC_READY",
    "Nursing Homes with CMS ownership-change history": "CONDITIONAL",
    "CMS provider types researched": "PUBLIC_READY",
    "Source freshness status": "CONDITIONAL",
    "Total Senior Providers": "DO_NOT_USE",
    "Best Senior Providers": "DO_NOT_USE",
    "Providers With Problems": "DO_NOT_USE",
    "Ownership Turnover Rate": "DO_NOT_USE",
    "National Senior Quality Score": "DO_NOT_USE",
}
