export type GoldenOutcome =
  | "PASS"
  | "PARTIAL"
  | "NEEDS_CLARIFICATION"
  | "UNSUPPORTED_SAFE"
  | "FAIL";
export type SeniorGoldenQuestion = { query: string; expected: GoldenOutcome };

export const SENIOR_SEARCH_GOLDEN_QUESTIONS: SeniorGoldenQuestion[] = [
  { query: "CMS CCN 105502", expected: "PASS" },
  { query: "Find CMS CCN 105502", expected: "PASS" },
  { query: "105502", expected: "UNSUPPORTED_SAFE" },
  { query: "Palm Garden of Tampa", expected: "PARTIAL" },
  { query: "Find Palm Garden of Tampa", expected: "PARTIAL" },
  { query: "nursing homes in Florida", expected: "PASS" },
  { query: "nursing homes in Palm Beach County", expected: "PASS" },
  { query: "nursing homes in Broward County", expected: "PASS" },
  { query: "home health agencies in Florida", expected: "PASS" },
  { query: "hospice providers in Florida", expected: "PASS" },
  { query: "assisted living facilities in Arizona", expected: "PARTIAL" },
  { query: "nursing homes in Colorado", expected: "PASS" },
  { query: "home health agencies in Colorado", expected: "PASS" },
  { query: "hospice providers in Colorado", expected: "PASS" },
  { query: "assisted living facilities in Colorado", expected: "PARTIAL" },
  { query: "nursing homes in Virginia", expected: "PASS" },
  { query: "home health agencies in Virginia", expected: "PASS" },
  { query: "hospice providers in Virginia", expected: "PASS" },
  { query: "assisted living in Virginia", expected: "PARTIAL" },
  { query: "does this assisted living facility have complaints?", expected: "PARTIAL" },
  { query: "how many senior care providers in Virginia", expected: "UNSUPPORTED_SAFE" },
  { query: "best nursing home in Virginia", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes in New York", expected: "PASS" },
  { query: "home health agencies in New York", expected: "PASS" },
  { query: "hospice providers in New York", expected: "PASS" },
  { query: "assisted living in New York", expected: "PARTIAL" },
  { query: "licensed home care agency in New York", expected: "PARTIAL" },
  { query: "complaints against this nursing home in New York", expected: "PARTIAL" },
  { query: "how many senior care providers in New York", expected: "UNSUPPORTED_SAFE" },
  { query: "best nursing home in New York", expected: "UNSUPPORTED_SAFE" },
  { query: "how many senior care providers in Colorado", expected: "UNSUPPORTED_SAFE" },
  { query: "best nursing home in Colorado", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes in Boca Raton", expected: "NEEDS_CLARIFICATION" },
  { query: "home health agencies in Palm Beach County", expected: "UNSUPPORTED_SAFE" },
  { query: "hospice providers in Miami", expected: "NEEDS_CLARIFICATION" },
  { query: "5 CMS overall star nursing homes in Florida", expected: "PASS" },
  { query: "nursing homes with 5 staffing stars", expected: "PASS" },
  { query: "nursing homes with 5 health inspection stars", expected: "PASS" },
  { query: "what does CMS overall star mean", expected: "PASS" },
  { query: "what does staffing star mean", expected: "PASS" },
  { query: "5 star hospice in Florida", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes with the most indexed deficiencies", expected: "PASS" },
  { query: "nursing homes with civil monetary penalties", expected: "PASS" },
  { query: "nursing homes with payment denials", expected: "PARTIAL" },
  { query: "nursing homes with staffing HPRD", expected: "PASS" },
  { query: "nursing homes with CHOW records", expected: "PASS" },
  { query: "nursing homes with ownership changes", expected: "PASS" },
  { query: "who owns this nursing home", expected: "NEEDS_CLARIFICATION" },
  { query: "nursing homes owned by Brookdale", expected: "PASS" },
  { query: "ownership organizations connected to the most nursing homes", expected: "PASS" },
  { query: "home health agencies with HHCAHPS evidence", expected: "PASS" },
  { query: "hospice providers with CAHPS evidence", expected: "PASS" },
  { query: "how many nursing homes are there", expected: "PASS" },
  { query: "how many nursing homes in Florida", expected: "PASS" },
  { query: "how many home health agencies in Florida", expected: "PASS" },
  { query: "how many hospice providers in Florida", expected: "PASS" },
  { query: "how many senior care providers are there", expected: "UNSUPPORTED_SAFE" },
  { query: "33,819 senior providers", expected: "UNSUPPORTED_SAFE" },
  { query: "distribution of nursing homes by CMS stars in Florida", expected: "PASS" },
  { query: "compare nursing home counts in Broward and Palm Beach", expected: "PASS" },
  { query: "compare nursing home staffing in Broward and Palm Beach", expected: "PASS" },
  { query: "best nursing home in Florida", expected: "UNSUPPORTED_SAFE" },
  { query: "safest nursing home", expected: "UNSUPPORTED_SAFE" },
  { query: "worst nursing home", expected: "UNSUPPORTED_SAFE" },
  { query: "most dangerous nursing home", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes with no deficiencies", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes with no penalties", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes with a clean record", expected: "UNSUPPORTED_SAFE" },
  { query: "good standing nursing homes", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes serving my ZIP code", expected: "UNSUPPORTED_SAFE" },
  { query: "home health agency serving Broward County", expected: "UNSUPPORTED_SAFE" },
  { query: "hospice serving my address", expected: "UNSUPPORTED_SAFE" },
  { query: "I need a nursing home for my mother in Boca Raton", expected: "NEEDS_CLARIFICATION" },
  { query: "I need home health for my father", expected: "PASS" },
  { query: "I want to research a hospice provider", expected: "PASS" },
  { query: "How do I check nursing home deficiencies", expected: "PASS" },
  { query: "Has this nursing home been fined", expected: "NEEDS_CLARIFICATION" },
  { query: "Did this facility change owners", expected: "NEEDS_CLARIFICATION" },
  { query: "Who owns this facility", expected: "NEEDS_CLARIFICATION" },
  { query: "Is a 5-star nursing home safe", expected: "UNSUPPORTED_SAFE" },
  { query: "Which nursing home should I choose", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing home with best staffing", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing home with highest CMS overall stars", expected: "PASS" },
  { query: "nursing home with lowest deficiencies", expected: "UNSUPPORTED_SAFE" },
  { query: "memory care in Florida", expected: "UNSUPPORTED_SAFE" },
  { query: "CCRC in Florida", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes on a watch list", expected: "UNSUPPORTED_SAFE" },
  { query: "generator compliance nursing homes", expected: "UNSUPPORTED_SAFE" },
  { query: "Home Health CHOW records", expected: "UNSUPPORTED_SAFE" },
  { query: "Hospice CHOW records", expected: "UNSUPPORTED_SAFE" },
  { query: "what is CHOW", expected: "PASS" },
  { query: "nursing home inspections in Florida", expected: "PARTIAL" },
  { query: "fire citations nursing homes in Florida", expected: "PARTIAL" },
  { query: "home health agencies with 5 Quality of Patient Care stars", expected: "PASS" },
  { query: "hospice overall CMS stars", expected: "UNSUPPORTED_SAFE" },
  { query: "all senior providers total", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes near my address", expected: "UNSUPPORTED_SAFE" },
  { query: "nursing homes in Texas", expected: "PASS" },
  { query: "hospice providers in Washington", expected: "PASS" },
  { query: "home health agencies in California", expected: "PASS" },
  { query: "nursing homes in New Jersey", expected: "PASS" },
  { query: "what is a deficiency", expected: "UNSUPPORTED_SAFE" },
  { query: "compare hospice stars and nursing home stars", expected: "UNSUPPORTED_SAFE" },
  { query: "<script>alert(1)</script>", expected: "UNSUPPORTED_SAFE" },
  { query: "' OR 1=1 --", expected: "UNSUPPORTED_SAFE" },
  { query: "", expected: "UNSUPPORTED_SAFE" },
  { query: "x".repeat(181), expected: "UNSUPPORTED_SAFE" },
];
